---
title: "Matrix Operation Functions"
author: "Mitul Mundra"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Matrix Operation Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

# Organization of Data for Matrix Operation Functions
--------

In order to use the matrix functions in FuzzyRMatrix package, it is necessary for the input table to be in a deep format. The deep format for organization of matrix data is explained as follows.

| MatrixID | Row_ID | Col_ID | Cell_Val |
|---------:|-------:|-------:|---------:|
|     1    |   1    |    1   |  1.426   |
|     1    |   1    |    2   |  2.310   |
|     1    |   2    |    1   |  7.080   |
|     1    |   2    |    2   |  5.475   |

The MatrixID is a non-unique primary identifier for the input matrix.  The Row_ID and Col_ID columns represent the row number and the column number of the matrix. The Row_ID and
Col_ID combination must be unique. Finally, the Cell_Val represents the value in that particular cell.

The following illustration explains the relation of the matrix and the deep table.

Matrix:

+------------+-----------+-----------+-----------+
| **Row ID** | **Col 1** | **Col 2** | **Col 3** |
+============+===========+===========+===========+
| **Row 1**  |   0.22    |   0.50    |   0.56    |
+------------+-----------+-----------+-----------+
| **Row 2**  |   0.28    |   0.27    |   0.13    |
+------------+-----------+-----------+-----------+
| **Row 3**  |   0.62    |   0.76    |   0.05    |
+------------+-----------+-----------+-----------+

Matrix in deep table format:

| MatrixID | Row_ID | Col_ID | Cell_Val |
|---------:|-------:|-------:|---------:|
|     1    |   1    |    1   |   0.22   |
|     1    |   1    |    2   |   0.50   |
|     1    |   1    |    3   |   0.56   |
|     1    |   2    |    1   |   0.28   |
|     1    |   2    |    2   |   0.27   |
|     1    |   2    |    3   |   0.13   |
|     1    |   3    |    1   |   0.62   |
|     1    |   3    |    2   |   0.76   |
|     1    |   3    |    3   |   0.05   |

In this deep format, it is expected that a specific row and column will not be duplicated.

In the current version of the package FuzzyRMatrix, there are two limitations for matrix functions and they are listed as below.
1. The matrix functions do not support complex Eigenvalues. This functionality will be provided in a subsequent release.
1. Matrices with extreme dimensions cannot be handled. Please refer to the Constraints section in each Matrix Operations function for details.


