#' Cholesky Decomposition of a matrix
#'
#' Cholesky decomposition is a decomposition of a positive definite matrix
#' into the product of a lower triangular matrix and its conjugate transpose.
#' \code{FLCholeskyDecomp} computes the lower triangular matrix generated by
#' Cholesky decomposition.
#' @section Constraints:
#' Input can only be a positive definite matrix (n x n) with maximum dimension
#' limitations of (1000 x 1000).
#' @param matrix an object of class FLMatrix.
#' @return \code{FLCholeskyDecomp} returns an object of class FLMatrix mapped
#' to the lower triangular matrix generated by Cholesky decomposition, which
#' can be pulled to R using \code{FLFetchMatrix}.
#' @examples
#' \dontrun{
#' library(RODBC)
#' connection      <- odbcConnect("Gandalf");
#' database        <- "FL_R_WRAP";
#' matrix_table    <- "tblMatrixMulti";
#' matrix_id_value <- 5;
#' in_matrix       <- FLMatrix(connection, database, matrix_table, matrix_id_value,
#'                    matrix_id = "Matrix_ID", row_id = "Row_ID", column_id = "Col_ID",
#'                    cell_value = "Cell_Val")
#' out_matrix      <- FLCholeskyDecomp(in_matrix)
#' }
#' @export
FLCholeskyDecomp <- function(matrix)
{
	matrixTable   <- matrix@matrix_table
	matrixIDValue <- toString(matrix@matrix_id_value)
	connection    <- matrix@ODBC_connection
	outTable      <- gen_out_matrix_table("CholeskyDecomp",matrixTable, matrixIDValue)

	sqlParameters <- list(	matrixIDValue = toString(matrix@matrix_id_value),
							rowID         = matrix@row_id,
							columnID      = matrix@column_id,
							cellValue     = matrix@cell_value,
							matrixTable   = matrix@matrix_table,
							outTable      = outTable)
	run_sql(connection, "FLCholeskyDecomp.sql", sqlParameters)

	retData = new("FLMatrix", 	ODBC_connection = connection, database = matrix@database,
								matrix_table = outTable, matrix_id_value = matrix@matrix_id_value,
								matrix_id = "OutputMatrixID", row_id = "OutputRowNum",
								column_id = "OutputColNum", cell_value = "OutputVal")
	return(retData)
}



