#' @include utilities.R
#' @include data_prep.R
#' @include FLTable.R

NULL

## move to file datamining.R
#' An S4 class to represent FLLinRegr
#'
#' @slot offset this can be used to specify a priori known component to be included in the 
#' linear predictor during fitting. This should be NULL or a numeric vector of length equal to the number of cases
#' An S4 class to represent objects returned by Data-Mining functions
#'
#' @slot deeptable A character vector containing a deeptable (either conversion from a 
#' widetable or input deeptable)
#' @slot AnalysisID An output character ID from call to data-mining function
#' @slot wideToDeepAnalysisId An output character ID from FLRegrDataPrep
#' @slot mapTable A character string name for the mapping table in-database if input is wide-table, generated by FLRegrDataPrep
#' @slot results cache list of results computed
#' @slot table Input data object
#' @export
setClass("FLDataMining",
		slots=list(AnalysisID="character",
				wideToDeepAnalysisId="character",
				table="FLTable",
				results="list",
				deeptable="FLTable",
				mapTable="character"))

#' An S4 class to represent objects returned by Regression Functions
#'
#' @slot formula an object of class 'formula': Model Formula
#' @slot scoreTable Name of the in-database table where scoring results are stored
#' @export
setClass("FLRegr",
		contains="FLDataMining",
		slots=list(formula="formula",
					scoreTable="character",
                    RegrDataPrepSpecs="list"))

#' An S4 class to represent output from Linear Regression(lm) on in-database Objects
#'
#' @slot offset column name used as offset
#' @slot vfcalls information about system tables
#' @method print FLLinRegr
#' @method coefficients FLLinRegr
#' @method residuals FLLinRegr
#' @method influence FLLinRegr
#' @method lm.influence FLLinRegr
#' @method plot FLLinRegr
#' @method summary FLLinRegr
#' @method predict FLLinRegr
#' @export
setClass(
	"FLLinRegr",
	contains="FLRegr",
	slots=list(offset="character",
				vfcalls="character"))

## move to file lm.R
#' Linear Regression.
#'
#' \code{lm} performs linear regression on FLTable objects.
#'
#' The DB Lytix function called is FLLinRegr. Performs Linear Regression and 
#' stores the results in predefined tables.
#'
#' @seealso \code{\link[stats]{lm}} for R reference implementation.
#' @param formula A symbolic description of model to be fitted
#' @param data An object of class FLTable or FLTableMD
#' @param catToDummy Transform categorical variables to numerical values
#' either using dummy variables or by using Empirical
#' Logit. If the value is 1, transformation is done using
#' dummy variables, else if the value is 0,
#' transformation is done using Empirical Logit.
#' @param performNorm 0/1 indicating whether to perform standardization of data.
#' @param performVarReduc 0/1. If the value is 1,
#' the stored procedure eliminates variables based on standard deviation and
#' correlation.
#' @param makeDataSparse If 0,Retains zeroes and NULL values
#' from the input table. If 1, Removes zeroes and NULL. If 2,Removes zeroes 
#' but retains NULL values.
#' @param minStdDev Minimum acceptable standard deviation for
#' elimination of variables. Any variable that has a
#' standard deviation below this threshold is
#' eliminated. This parameter is only consequential if
#' the parameter PerformVarReduc = 1. Must be >0.
#' @param maxCorrel Maximum acceptable absolute correlation between
#' a pair of columns for eliminating variables. If the
#' absolute value of the correlation exceeds this
#' threshold, one of the columns is not transformed.
#' Again, this parameter is only consequential if the
#' parameter PerformVarReduc = 1. Must be >0 and <=1.
#' @param classSpec list describing the categorical dummy variables.
#' @param whereconditions takes the where_clause as a string.
#' @section Constraints:
#' The anova method is not yet available for FLLinRegr
#' If \code{data} is FLTableMD, only single formula is accepted.
#' So input deeptable or deeptable produced after data preparation
#' should have same VarIDs'.
#' For FLTableMD data object, only coefficients and summary
#' methods are defined.Predict method on \code{FLTableMD}
#' \code{newdata} is not supported.
#' Properties like \code{print(x),model,plot} might take time as they
#' have to fetch data
#' @return \code{lm} returns an object of class \code{FLLinRegr}
#' @examples
#' widetable  <- FLTable("tblAbaloneWide", "ObsID")
#' lmfit <- lm(Rings~Height+Diameter,widetable)
#' lmfit$coefficients
#' lmfit$fitted.values
#' plot(lmfit)
#' mu <- predict(lmfit,newdata=widetable)
#' deeptable <- FLTable("myLinRegrSmall","ObsID","VarID","Num_Val")
#' lmfit <- lm(NULL,deeptable)
#' summary(lmfit)
#' flMDObject <- FLTableMD(table="tblAutoMPGMD",
#'                       group_id_colname="GroupID",
#'                       obs_id_colname="ObsID",group_id = c(2,4))
#' vformula <- MPG~HorsePower+Displacement+Weight+Acceleration
#' lmfit <- lm(vformula,
#'            data=flMDObject)
#' coeffList <- coef(lmfit)
#' summaryList <- summary(lmfit)
#' @export
lm <- function (formula,data=list(),...) {
	UseMethod("lm", data)
 }

## move to file lm.R
#' @export
lm.default <- stats::lm

## move to file lm.R
#' @export
lm.FLpreparedData <- function(formula,data,...)
{
	vcallObject <- match.call()
	return(lmGeneric(formula=formula,
                     data=data,
                     callObject=vcallObject,
                     familytype="linear",
                     ...))
}

## move to file lm.R
#' @export
lm.FLTable <- function(formula,data,...)
{
	vcallObject <- match.call()
	data <- setAlias(data,"")
	return(lmGeneric(formula=formula,
                     data=data,
                     callObject=vcallObject,
                     familytype="linear",
                     ...))
}

#' @export
lm.FLTableMD <- function(formula,data,...)
{
	vcallObject <- match.call()
	data <- setAlias(data,"")
	return(lmGeneric(formula=formula,
                     data=data,
                     callObject=vcallObject,
                     familytype="linear",
                     ...))
}

## move to file step.R
#' Choose a model.
#'
#' \code{steps} performs linear regression on FLTable objects.
#' Choose a formula based model by p-values and R-Squared Values.
#'
#' @seealso \code{\link[stats]{step}} for R reference implementation.
#'
#' @param object An object of class FLTable
#' @param scope A symbolic description of model to be fitted.
#' \code{scope} can be a list with upper and lower components
#' or a formula. For a widetable, upper and lower should be formulas
#' describing the range of models. If a formula is given instead of list
#' it will be treated as upper. For a deeptable, upper and lower should
#' be vectors with variable ids'.Provide empty list for deeptable if 
#' nothing is to be specified.
#' @param scale currently not used.
#' @param direction character.Must be one of backward,
#' Fbackward,UFbackward,forward.
#' @param trace if positive, information is printed out during the
#' running of the steps.
#' @param catToDummy Transform categorical variables to numerical values
#' either using dummy variables or by using Empirical
#' Logit. If the value is 1, transformation is done using
#' dummy variables, else if the value is 0,
#' transformation is done using Empirical Logit.
#' @param performNorm 0/1 indicating whether to perform standardization of data.
#' @param performVarReduc 0/1. If the value is 1,
#' the stored procedure eliminates variables based on standard deviation and
#' correlation.
#' @param makeDataSparse If 0,Retains zeroes and NULL values
#' from the input table. If 1, Removes zeroes and NULL. If 2,Removes zeroes 
#' but retains NULL values.
#' @param minStdDev Minimum acceptable standard deviation for
#' elimination of variables. Any variable that has a
#' standard deviation below this threshold is
#' eliminated. This parameter is only consequential if
#' the parameter PerformVarReduc = 1. Must be >0.
#' @param maxCorrel Maximum acceptable absolute correlation between
#' a pair of columns for eliminating variables. If the
#' absolute value of the correlation exceeds this
#' threshold, one of the columns is not transformed.
#' Again, this parameter is only consequential if the
#' parameter PerformVarReduc = 1. Must be >0 and <=1.
#' @param classSpec list describing the categorical dummy variables.
#' @param whereconditions takes the where_clause as a string.
#' @param highestpAllow1 All the variables whose p-value exceed the value
#' specified by HighestpAllow1 are dropped in one go. 
#' Typical value for HighestProbAllow1 could be 0.50. Must be >0 and < 1.
#' Not applicable for forward.
#' @param highestpAllow2 Only one variable is dropped at a time
#' till all the p-Values are below the HighestpAllow2.
#' Typical value could be 0.10. Must be >0 and < 1.
#' Not applicable for forward and backward.
#' @param stepWiseDecrease The StepwiseDecrease is used to
#' decrease the p-Value at each stage. In first step, 
#' all variables having pValue exceeding HighestpValue1 are
#' dropped. Then the HighestpValue1 is
#' reduced by StepwiseDecreasepValue
#' and the process is repeated until all
#' the variables have p-value less than HighestpValue2.
#' Must be >0 and <1. Used only for UFbackward.
#' @section Constraints:
#' The anova method is not yet available for FLLinRegr.
#' Properties like \code{print(fit$x),model,plot} might take time as they
#' have to fetch data
#' 
#' @return \code{step} performs linear regression and replicates equivalent R output.
#' @examples
#' widetable  <- FLTable("tblAbaloneWide", "ObsID")
#' s <- step(widetable,scope=list(lower=Rings~Height+Diameter),direction = "UFbackward")
#' plot(s)
#' s$coefficients
#' s <- step(widetable,
#' 			scope=list(lower=Rings~Height+Diameter,
#'  					upper=Rings~Height+Diameter+Sex+Num_Length),
#' 			direction = "UFbackward")
#' plot(s)
#' s$coefficients
#' s <- step(widetable,scope=list(lower=Rings~Num_Length),
#' 			direction = "UFbackward",performNorm=1,performVarReduc=1,maxCorrel=0.6)
#' plot(s)
#' s$coefficients
#' s <- step(widetable,
#' 			scope=list(upper=Rings~Height+Diameter+Sex+Num_Length+DummyCat),
#'  		direction = "Fbackward")
#' plot(s)
#' s$coefficients
#' s <- step(widetable,
#' 			scope=Rings~Height+Diameter+Sex+Num_Length+DummyCat,
#'  		direction = "forward")
#' plot(s)
#' s$coefficients
#' s <- step(widetable,
#' 			scope=Rings~Height+Diameter+Sex+Num_Length+DummyCat,
#'  		direction = "Fbackward")
#' plot(s)
#' s$coefficients
#' s <- step(widetable,
#' 			scope=list(upper=Rings~Height+Diameter+Sex+Num_Length+DummyCat),
#'  		direction = "forward")
#' plot(s)
#' s$coefficients
#' deeptable <- FLTable("myLinRegrSmall","ObsID","VarID","Num_Val")
#' s <- step(deeptable,
#' 			scope=list(upper=c("-1","0","1")),
#'  		direction = "backward")
#' s <- step(deeptable,
#' 			scope=list(upper=c("1","2"),lower=c("1")),
#'  		direction = "Fbackward")
#' s <- step(deeptable,
#' 			scope=list(lower=c("2")),
#'  		direction = "UFbackward")
#' s <- step(deeptable,
#' 			scope=list(),
#'  		direction = "forward")
#' deeptable1 <- FLTable("tblLogRegr",
#' 					"ObsID","VarID","Num_Val",
#'                   whereconditions=c("ObsID < 7001","VarID<5"))
#' s <- step(deeptable1,
#'          scope=list(lower=c("2")),
#'          direction = "UFbackward",familytype = "logistic")
#' s <- step(deeptable1,
#' 			scope=list(),
#'  		direction = "forward",familytype="logistic")
#' plot(s)
#' s <- step(deeptable1,
#' 			scope=list(upper=c("-1","0","1","2","3")),
#'  		direction = "backward",
#' 			familytype="multinomial",pRefLevel=1)
#' s <- step(deeptable1,
#' 			scope=list(upper=c("1","2","3"),lower=c("2")),
#'  		direction = "Fbackward",familytype="multinomial",pRefLevel=1)
#' deeptable2 <- FLTable("tblLogRegrMN10000",
#' 					"ObsID","VarID","Num_Val",
#'                   whereconditions=c("ObsID < 7001","VarID<5"))
#' s <- step(deeptable2,
#'          scope=list(lower=c("2")),
#'          direction = "UFbackward",familytype = "multinomial",pRefLevel=1)
#' summary(s)
#' @export
step <- function (object,scope,...){
	UseMethod("step", object)
}

## move to file step.R
#' @export
step.default <- stats::step

## move to file step.R
#' @export
step.FLTable <- function(object, scope, scale = 0,
     				direction = "forward",
     				trace = 1,
     				familytype="linear",
     				...){

	if (!direction %in% c("forward","Fbackward","backward","UFbackward"))
	stop("direction must be in c(forward,Fbackward,backward,UFbackward)")
	if(!is.list(scope) && !class(scope)=="formula")
	stop("scope argument must be a list or formula.\n",
		" empty list accepted for deeptable.\n")
	if(!familytype %in% c("linear","logistic","multinomial"))
	stop("familytype argument must be one of linear,logistic or multinomial",
		"in step.FLTable\n")
	if(familytype=="multinomial" && direction=="forward")
	stop("forward not supported in multinomial logistic regr currently")
	vupperformula <- ""
	if(class(scope)=="formula")
	{
		if(isDotFormula(scope))
			scope <- genDeepFormula(pColnames=setdiff(colnames(object),
                                                      getVariables(object)[["obs_id_colname"]]),
									pDepColumn=ifelse(object@isDeep,
													NULL,
													all.vars(scope)[1]))
		vupperformula <- scope
	}

	object <- setAlias(object,"")

	vinclude <- c()
	vexclude <- c()
	if(is.list(scope))
	{#browser()
		vlower <- scope[["lower"]]
		vupper <- scope[["upper"]]

		## To account for . in formula
		if(isDotFormula(vlower))
		vlower <- genDeepFormula(pColnames=setdiff(colnames(object),
                                                      getVariables(object)[["obs_id_colname"]]),
								pDepColumn=ifelse(object@isDeep,
													NULL,
													all.vars(vlower)[1]))
		if(isDotFormula(vupper))
		vupper <- genDeepFormula(pColnames=setdiff(colnames(object),
                                                      getVariables(object)[["obs_id_colname"]]),
								pDepColumn=ifelse(object@isDeep,
													NULL,
													all.vars(vupper)[1]))

		##If only lower is given. Upper includes all.
		if(is.null(vupper) && !is.null(vlower)){
			if(!object@isDeep){
				if(class(vlower)!="formula") stop("for wide table scope should have formula as components\n")
				vupperformula <- formula(paste0(all.vars(vlower)[1],"~",
									paste0(setdiff(colnames(object),
										c(all.vars(vlower)[1],
											getVariables(object)[["obs_id_colname"]])),
									collapse="+")))
				vinclude <- all.vars(vlower)[2:length(all.vars(vlower))]
			}
			else{
				if(!is.vector(vlower)) stop("for deep table scope should have vectors as components\n")
				vinclude <- vlower
			}
		}
		else if(is.null(vlower) && !is.null(vupper)){
			if(!object@isDeep){
				if(class(vupper)!="formula") stop("for wide table scope should have formula as components\n")
				vupperformula <- vupper
			}
			else{
				if(!is.vector(vupper)) stop("for deep table scope should have vectors as components\n")
				vexclude <- setdiff(colnames(object),vupper)
			}
		}
		else if(!is.null(vupper) && !is.null(vlower)){
			if(!object@isDeep){
				if(class(vupper)!="formula" || class(vlower)!="formula")
				stop("for wide table scope should have formula as components\n")
				vupperformula <- vupper
				vinclude <- all.vars(vlower)[2:length(all.vars(vlower))]
			}
			else{
				if(!is.vector(class(vupper)) || !is.vector(class(vlower)))
				stop("for deep table scope should have vectors as components\n")
				vinclude <- vlower
				vexclude <- setdiff(colnames(object),vupper)
			}	
		}
		else if(!object@isDeep) stop("scope cannot be empty list for widetable")
	}

	vinclude <- setdiff(vinclude,c("-1"))
	vexclude <- setdiff(vexclude,c("0","-1"))
	if(!length(vinclude)>0) vinclude <- NULL
	if(!length(vexclude)>0) vexclude <- NULL

	if(!is.null(vinclude) || !is.null(vexclude))
	specID <- list(include=vinclude,
					exclude=vexclude)
	else specID <- list()

	vcallObject <- match.call()
	return(lmGeneric(formula=vupperformula,
					data=object,
					callObject=vcallObject,
					familytype=familytype,
					specID=specID,
					direction=direction,
					trace=trace,
					...))
}

## move to file lmGeneric.R
lmGeneric <- function(formula,data,
                      callObject=NULL,
                      familytype="linear",
                      specID=list(),
                      direction="",
                      trace=1,
                      ...)
{
    ##browser()
    if(inherits(data,"FLTable"))
        prepData <- prepareData.lmGeneric(formula,data,
                                          callObject=callObject,
                                          familytype=familytype,
                                          specID=specID,
                                          direction=direction,
                                          trace=trace,
                                          ...)
    else if(inherits(data,"FLpreparedData")){
        prepData <- data
        data <- prepData$wideTable
    }
	for(i in names(prepData))
	assign(i,prepData[[i]])
	# deepx <- prepData[["deepx"]]
	# vmapping <- prepData[["vmapping"]]
	# formula <- prepData[["formula"]]
	# wideToDeepAnalysisId <- prepData[["wideToDeepAnalysisId"]]
	# mapTable <- prepData[["mapTable"]]
	# vspecID <- prepData[["vspecID"]]
	# highestpAllow1 <- prepData[["highestpAllow1"]]
	# highestpAllow2 <- prepData[["highestpAllow2"]]
	# topN <- prepData[["topN"]]
	# stepWiseDecrease <- prepData[["stepWiseDecrease"]]
	# vexclude <- prepData[["vexclude"]]
	# vallVars <- prepData[["vallVars"]]
	# pThreshold <- prepData[["pThreshold"]]
	# eventweight <- prepData[["eventweight"]]
	# noneventweight <- prepData[["noneventweight"]]
	# maxiter <- prepData[["maxiter"]]
	# offset <- prepData[["offset"]]

	deeptable <- deepx@select@table_name

	if(familytype=="linear") vfcalls <- c(functionName=ifelse(is.FLTableMD(data),
															"FLLinRegrMultiDataset",
															"FLLinRegr"),
										infotableName="fzzlLinRegrInfo",
										note="linregr",
										coefftablename="fzzlLinRegrCoeffs",
										statstablename="fzzlLinRegrStats",
										valcolnamescoretable="Y",
										scoretablename="FLLinRegrScore")
	else if(familytype=="logistic") vfcalls <- c(functionName=ifelse(is.FLTableMD(data),
																	"FLLogRegrMultiDataset",
																	"FLLogRegr"),
										infotableName="fzzlLogRegrInfo",
										note="logregr",
										coefftablename="fzzlLogRegrCoeffs",
										statstablename="fzzlLogRegrStats",
										valcolnamescoretable="Y",
										scoretablename="FLLogRegrScore")
	else if(familytype=="poisson") vfcalls <- c(functionName="FLPoissonRegr",
										infotableName="fzzlPoissonRegrInfo",
										note="poissonregr",
										coefftablename="fzzlPoissonRegrCoeffs",
										statstablename="fzzlPoissonRegrStats",
										valcolnamescoretable="Mu",
										scoretablename="FLPoissonRegrScore")
	else if(familytype=="logisticwt"){
		vfcalls <- c(functionName="FLLogRegrWt",
										infotableName="fzzlLogRegrInfo",
										note="logregrwt",
										coefftablename="fzzlLogRegrCoeffs",
										statstablename="fzzlLogRegrStats",
										valcolnamescoretable="Y",
										scoretablename="FLLogRegrScore")
		vtemp <- pThreshold
		pThreshold <- maxiter
		maxiter <- vtemp
	}
	else if(familytype=="multinomial") vfcalls <- c(functionName="FLLogRegrMN",
										infotableName="fzzlLogRegrMNInfo",
										note="logregrMN",
										coefftablename="fzzlLogRegrMNCoeffs",
										statstablename="fzzlLogRegrMNStats",
										valcolnamescoretable="Y",
										scoretablename="FLLogRegrScore")

	functionName <- vfcalls["functionName"]
	infotableName <- vfcalls["infotableName"]
	vnote <- genNote(vfcalls["note"])
	coefftablename <- vfcalls["coefftablename"]
	statstablename <- vfcalls["statstablename"]

	vinputCols <- list()
	if(functionName %in% c("FLLinRegrMultiDataset",
							"FLLogRegrMultiDataset"))
		vinputCols <- c(vinputCols,
						INPUT_TABLE=deeptable,
						GroupIDCol=getVariables(deepx)[["group_id_colname"]],
						OBSID_COL=getVariables(deepx)[["obs_id_colname"]],
						VARID_COL=getVariables(deepx)[["var_id_colname"]],
						VALUE_COL=getVariables(deepx)[["cell_val_colname"]]
						)
	else vinputCols <- c(vinputCols,
						INPUT_TABLE=deeptable,
						OBSID_COL=getVariables(deepx)[["obs_id_colname"]],
						VARID_COL=getVariables(deepx)[["var_id_colname"]],
						VALUE_COL=getVariables(deepx)[["cell_val_colname"]]
						)
	if(familytype %in% "multinomial")
	vinputCols <- c(vinputCols,
					pRefLevel=pThreshold)
	if(!familytype %in% "linear" && direction!="forward")
	vinputCols <- c(vinputCols,
					MAX_ITER=maxiter)
	if(base::grepl("logistic",familytype) 
		&& direction!="forward")
	vinputCols <- c(vinputCols,
					THRESHOLD=pThreshold)
	if(direction==""){
		vfuncName=functionName
		if(familytype %in% "logisticwt")
		vinputCols <- c(vinputCols,
						EVENTWEIGHT=eventweight,
						NONEVENTWEIGHT=noneventweight)
	}
	if(direction %in% c("backward","Fbackward","UFbackward")){
		vfuncName <- paste0(functionName,"BW")
		vinputCols <- c(vinputCols,
						SPECID=vspecID,
						HIGHESTPALLOW1=highestpAllow1)
	}
	if(direction %in% c("Fbackward","UFbackward")){
		vfuncName <- paste0(functionName,"FB")
		vinputCols <- c(vinputCols,
						HIGHESTPALLOW2=highestpAllow2)
	}
	if(direction %in% c("UFbackward")){
		vfuncName <- paste0(functionName,"UFB")
		vinputCols <- c(vinputCols,
						STEPWISEDECREASE=stepWiseDecrease)
	}
	if(direction %in% c("forward")){
		vfuncName <- paste0(functionName,"SW")
		if(!familytype %in% "linear")
		vinputCols <- c(vinputCols,
						THRESHOLD=pThreshold)
		if(familytype %in% "logistic")
		vinputCols <- c(vinputCols,
					MAX_ITER=maxiter)
		vinputCols <- c(vinputCols,
						TOPN=topN,
						HIGHESTPALLOW1=highestpAllow1)
	}
	vinputCols <- c(vinputCols,
					NOTE=vnote)
	retobj <- sqlStoredProc(getFLConnection(),
							vfuncName,
							outputParameter=c(AnalysisID="a"),
							pInputParams=vinputCols
							)

	retobj <- checkSqlQueryOutput(retobj)
	AnalysisID <- as.character(retobj[1,1])

	##Find the max modelID to avoid joins later.
	##For forward find best fit model id.
	vmaxModelID <- NULL
	vmaxLevelID <- NULL
	if(direction=="" && familytype!="poisson" 
		&&!is.FLTableMD(data)){
		vmaxModelID <- 1
		vmaxLevelID <- 1
	}
	else if(!direction %in% "forward" && familytype!="poisson" && !is.FLTableMD(data)){
		vsqlstr <- paste0("SELECT MAX(ModelID) AS ModelID",
							ifelse(familytype=="multinomial",",MAX(LevelID) AS LevelID ",""),
							" FROM ",coefftablename," WHERE AnalysisID=",fquote(AnalysisID))
		vtemp <- sqlQuery(getFLConnection(),vsqlstr)
		vmaxModelID <- vtemp[["ModelID"]]
		vmaxLevelID <- vtemp[["LevelID"]]
	}
	
	if(trace>0 && !direction %in% c("","forward"))
	{
		vsqlstr <- paste0("SELECT a.coeffid,c.* \n",
						" FROM ",coefftablename," a,",statstablename," c \n",
						" WHERE NOT EXISTS(SELECT 1 FROM ",coefftablename," b ",
							" WHERE b.analysisid=a.analysisid AND b.modelid=a.modelid+1 \n",
							" AND a.coeffid = b.coeffid ",ifelse(!is.null(vmaxLevelID),
							" AND a.LevelID = b.LevelID ",""),")\n",
						" AND a.analysisid=",fquote(AnalysisID)," AND c.analysisid=a.analysisid \n",
						" AND a.modelid<>",vmaxModelID," AND c.modelid=a.modelid\n",
						ifelse(!is.null(vmaxLevelID),paste0(" AND a.LevelID = ",vmaxLevelID),""),
						" \n UNION ALL\n",
						" SELECT 0,a.* FROM ",statstablename," a \n",
						" WHERE a.AnalysisID=",fquote(AnalysisID),
						" AND a.ModelID=",vmaxModelID,"\n",
						" ORDER BY 3")
		d <- sqlQuery(getFLConnection(),vsqlstr)
		colnames(d)<-toupper(colnames(d))
		d[["ANALYSISID"]] <- NULL
		vdroppedCols <- c()
		if(!data@isDeep)vdroppedCols <- specID[["exclude"]]
		if(nrow(d)>1){
			for(i in unique(setdiff(d[["MODELID"]],vmaxModelID)))
			{
				if(familytype=="linear")
				cat("Step:    RSQUARED = ",d[d[,"MODELID"]==i,"RSQUARED"][1],"\n")
				else if(familytype=="logistic")
				cat("Step:    Gini Coefficient = ",d[d[,"MODELID"]==i,"GINICOEFF"][1],"\n")
				#browser()
				vdropped <- as.numeric(d[d[,"MODELID"]==i,"COEFFID"])
				vcolnames <- names(vmapping)
				vdroppedCols1 <- sapply(vdropped,function(x) vcolnames[as.numeric(vmapping)==x])
				if(!data@isDeep)vdroppedCols <- c(vdroppedCols1,vdroppedCols)
				if(data@isDeep){
					vallVars <- all.vars(formula)
					vfr <- genDeepFormula(c(vdropped))
					vdroppedCols <- c(vdroppedCols,all.vars(vfr)[-1])
					vdroppedCols1 <- all.vars(genDeepFormula(specID[["exclude"]]))[-1]
					vcolnames <- vallVars[!vallVars %in% vdroppedCols1]
				}
				cat(vallVars[1],"~",paste0(vcolnames[!toupper(vcolnames) %in% c(toupper(vdroppedCols)
					,toupper(vallVars[1]))],
					collapse=" + "),"\n")
				vdataframe <- rbind(d[d[,"MODELID"]==i,][1,],d[d[,"MODELID"]==i+1,][1,])
				rownames(vdataframe) <- c(" - None",paste0(" - ",paste0(vdroppedCols,collapse=" + ")))
				print(vdataframe[,!colnames(vdataframe) %in% c("COEFFID","BPSTAT","SIGBPSTAT")])
				cat("\n\n\n")
			}
		}
	}
	else if(direction %in% c("forward"))
	{
		if(familytype=="linear")
		vsqlstr <- paste0("SELECT TOP 1 a.*,b.maxPValue \n",
						  " FROM ",statstablename," a,( \n",
						  		" SELECT a.ModelID,",
						  		" MAX(a.PValue) AS maxPValue \n",
								" FROM ",coefftablename," a \n",
								" WHERE a.AnalysisID = ",fquote(AnalysisID),
								" GROUP BY a.ModelID) AS b \n",
								" WHERE b.ModelID = a.ModelID \n",
								" AND a.AnalysisID = ",fquote(AnalysisID),
								" AND b.MaxPValue < 0.10 \n",
								" ORDER BY 3 DESC, 2;\n")
		else if(familytype=="logistic")
		vsqlstr <- paste0("SELECT TOP 1 a.*\n",
						  " FROM ",statstablename," a\n",
								" WHERE a.AnalysisID = ",fquote(AnalysisID),
								" AND a.HighestPValue < 0.10 \n",
								" ORDER BY 3 DESC, 2;\n")

		d <- sqlQuery(getFLConnection(),vsqlstr)
		colnames(d) <- toupper(colnames(d))
		d[["ANALYSISID"]] <- NULL
		vmaxModelID <- d[["MODELID"]]
		if(trace>0) print(d)
	}

	vfuncName <- ifelse(familytype %in% c("logisticwt","poisson"),
					"FLLogRegr",functionName)
	vfuncName <- base::gsub("MultiDataset","",vfuncName)
	return(new(vfuncName,
				formula=formula,
				AnalysisID=AnalysisID,
				wideToDeepAnalysisId=wideToDeepAnalysisId,
				table=data,
				results=list(call=callObject,
							 modelID=vmaxModelID),
				deeptable=deepx,
				mapTable=mapTable,
				scoreTable="",
				vfcalls=vfcalls,
				offset=as.character(offset),
                RegrDataPrepSpecs=RegrDataPrepSpecs))
}

## move to file lmGeneric.R
#' @export
prepareData.lmGeneric <- function(formula,data,
								callObject=NULL,
								familytype="linear",
								specID=list(),
								direction="",
								trace=1,
								catToDummy=0,
								performNorm=0,
								performVarReduc=0,
								makeDataSparse=1,
								minStdDev=0,
								maxCorrel=1,
								classSpec=list(),
								whereconditions="",
								highestpAllow1=0.5,
								highestpAllow2=0.1,
								stepWiseDecrease=0.05,
								topN=1,
								pThreshold=0.1,
								eventweight=0.8,
								noneventweight=1,
								maxiter=25,
								offset="",
								pRefLevel=NULL,
                                fetchIDs=FALSE,
                                outDeepTableName="",
                                ...){
    data <- setAlias(data,"")
	if(data@isDeep){
		vallVars <- colnames(data)
		##For MultiDataset and deep data
		##colnames is a list
		##Assumption: All Models have same formula
		## Meaning same varIDs
		if(is.FLTableMD(data)){
			if(!length(unique(vallVars))==1)
				stop("Datasets should have same columns \n ")
			else vallVars <- vallVars[[1]][1]:vallVars[[1]][2]
		}
		formula <- genDeepFormula(vallVars)
	}
	else{
        if(isDotFormula(formula)){
            vexcludeCols <- NULL
            if("excludeCols" %in% names(list(...)))
                vexcludeCols <- list(...)$excludeCols
            formula <- genDeepFormula(pColnames=setdiff(colnames(data),
                                                c(vexcludeCols,
                                                getVariables(data)[["obs_id_colname"]])),
                                    pDepColumn=all.vars(formula)[1])
        }
		vallVars <- base::all.vars(formula)
		vdependent <- vallVars[1]
		vindependent <- vallVars[2:length(vallVars)]
		checkValidFormula(formula,data)
	}
	
	vcolnames <- colnames(data)
	wideToDeepAnalysisId <- ""
    mapTable <- ""

    if(offset!="" && !toupper(offset) %in% toupper(vcolnames))
    stop("offset not in colnames of data")

    check0To1 <- function(pObject)
    {
    	if(!is.numeric(pObject) || 
    		pObject < 0 ||
    		pObject > 1)
    	stop(names(pObject)," should be >0 and <1\n")
    }
    checkSpecID <- function(pObject,pAllVars)
    {
    	pObject <- c(pObject[["include"]],pObject[["exclude"]])
    	if(length(pObject)>0)
    	{
    		sapply(pObject,function(x)
	        if(!(x %in% pAllVars))
	        stop(paste0(x,collapse=",")," specified in SpecID not in colnames of data\n"))
    	}
    }

    maxiter <- maxiter[1]
    if(!is.numeric(maxiter) || maxiter<=0)
    stop("maxiter should be >0")
    maxiter <- as.integer(maxiter)

    if(familytype %in% c("logistic","logisticwt"))
    {
    	check0To1(c(pThreshold=pThreshold))
    	if(familytype %in% "logisticwt"){
    		check0To1(c(eventweight=eventweight))
    		check0To1(c(noneventweight=noneventweight))
    	}
    }
    
    if(is.FLTableMD(data)){
    	if(!familytype %in% c("logistic","linear"))
    		stop("only lm and glm with binomial family supported for MultiDataset\n")
    	direction <- ""
    }
    if(direction=="UFbackward")
    {
    	check0To1(c(highestpAllow1=highestpAllow1,
    				highestpAllow2=highestpAllow2,
    				stepWiseDecrease=stepWiseDecrease))
    	checkSpecID(specID,vallVars)
    }
    if(direction=="backward")
    {
    	check0To1(c(highestpAllow1=highestpAllow1))
    	checkSpecID(specID,vallVars)
    }
    if(direction=="forward")
    {
    	check0To1(c(highestpAllow1=highestpAllow1))
    	if(!is.numeric(topN) || as.integer(topN)<1 || as.integer(topN)>10)
    	stop("topN should be >0 and <=10")
    	topN <- as.integer(topN)
    }
    if(direction=="Fbackward")
    {
    	check0To1(c(highestpAllow1=highestpAllow1,
    				highestpAllow2=highestpAllow2))
    	checkSpecID(specID,vallVars)
    }

    if(!data@isDeep){
    	unused_cols <- setdiff(vcolnames,c(all.vars(formula),specID[["exclude"]]))
		unused_cols <- setdiff(unused_cols,
								c(getVariables(data)[["obs_id_colname"]],
								getVariables(data)[["group_id_colname"]]))
		## Detect factors and assign classSpec
		vfirstRow <- sqlQuery(getFLConnection(),
							limitRowsSQL(paste0("SELECT * FROM (",
									constructSelect(data),") a "),1))
		vfactorCols <- list()
		## apply(t,2,function(x){class(x[[1]])}) gives all character
		for(i in setdiff(colnames(vfirstRow),
						c(unused_cols,names(classSpec),
							getVariables(data)[["obs_id_colname"]],
							"obs_id_colname",
							getVariables(data)[["group_id_colname"]],
							"group_id_colname",
                            list(...)[["doNotTransform"]]))){
			if(length(i)==0) break;
			if(is.factor(vfirstRow[[i]]) 
				|| is.character(vfirstRow[[i]])
				|| is.logical(vfirstRow[[i]])){
				# if(is.logical(vfirstRow[[i]])){
				# 	vtemp <- levels(sqlQuery(getFLConnection(),
				# 					paste0("SELECT DISTINCT(",i,
				# 						") FROM(",constructSelect(data),") a "))[[1]])[1]
				# 	names(vtemp) <- i
				# 	classSpec <- c(classSpec,vtemp)
				# }
				# else{
					r<-as.character(vfirstRow[[i]])
			  		names(r) <- i
			  		vfactorCols <- c(vfactorCols,r)
				# }
			}
		}
		if(length(vfactorCols)>0){
			vrefVars <- sqlQuery(getFLConnection(),
							paste0("SELECT ",
								paste0("MIN(",names(vfactorCols),
									") AS ",names(vfactorCols),
									collapse=","),
								" FROM (",constructSelect(data),") a "))
			vtempList <- list()
            vrefVarNames <- names(vrefVars)
			for(i in colnames(vrefVars)){
                ## Remove variables with NA
                if(is.na(vrefVars[[i]]))
                    vrefVarNames <- setdiff(vrefVarNames,
                                            i)
                else if(is.logical(vrefVars[[i]]))
					vtempList <- c(vtempList,
									levels(sqlQuery(getFLConnection(),
												paste0("SELECT DISTINCT(",i,
												") FROM(",constructSelect(data),") a "))[[1]])[1])
				else vtempList <- c(vtempList,as.character(vrefVars[[i]]))
			}
			names(vtempList) <- vrefVarNames
			# vfactorCols[names(vrefVars)] <- as.list(apply(vrefVars[names(vrefVars)],
			# 											2,function(x){
			# 												browser()
			# 												if(is.logical(x))
			# 													return(levels(sqlQuery(getFLConnection(),
			# 																	paste0("SELECT DISTINCT(",names(x),
			# 																		") FROM(",constructSelect(data),") a "))[[1]])[1])
			# 												else as.character(x)
			# 											}))
			classSpec <- c(classSpec,vtempList)
		}
		
		vexcludeCols <- paste0(unused_cols,collapse=",")
    }
	
	vcallObject <- callObject
    vRegrDataPrepSpecs <- list()
	if(!data@isDeep)
	{
		deepx <- FLRegrDataPrep(data,depCol=vdependent,
								outDeepTableName=outDeepTableName,
								outObsIDCol="",
								outVarIDCol="",
								outValueCol="",
								catToDummy=catToDummy,
								performNorm=performNorm,
								performVarReduc=performVarReduc,
								makeDataSparse=makeDataSparse,
								minStdDev=minStdDev,
								maxCorrel=maxCorrel,
								trainOrTest=0,
								excludeCols=vexcludeCols,
								classSpec=classSpec,
								whereconditions=whereconditions,
								inAnalysisID="",
                                fetchIDs=fetchIDs)

        vRegrDataPrepSpecs <- list(outDeepTableName=outDeepTableName,
                                outObsIDCol="",
                                outVarIDCol="",
                                outValueCol="",
                                catToDummy=catToDummy,
                                performNorm=performNorm,
                                performVarReduc=performVarReduc,
                                makeDataSparse=makeDataSparse,
                                minStdDev=minStdDev,
                                maxCorrel=maxCorrel,
                                trainOrTest=0,
                                excludeCols=vexcludeCols,
                                classSpec=classSpec)

		wideToDeepAnalysisId <- deepx[["AnalysisID"]]
		deepx <- deepx[["table"]]
		deepx <- setAlias(deepx,"")
		whereconditions <- ""
		mapTable <- getRemoteTableName(tableName="fzzlRegrDataPrepMap", temporaryTable=FALSE)
		if(familytype=="poisson")
		{
			vtablename <- deepx@select@table_name
			vtablename1 <- data@select@table_name
			vobsid <- getVariables(data)[["obs_id_colname"]]
			sqlstr <- paste0(" SELECT ",vobsid," AS obs_id_colname,","\n               ",
							" -2 AS var_id_colname,","\n               ",
							ifelse(offset!="",offset,0)," AS cell_val_colname","\n        ",
							" FROM ",vtablename1)
			t <- insertIntotbl(pTableName=vtablename,
                                pSelect=sqlstr)
			deepx@Dimnames[[2]] <- c("-2",deepx@Dimnames[[2]])
		}
		
		##Get Mapping Information for specID
		if(!is.FLTableMD(data)){
			vmapping <- sqlQuery(getFLConnection(),
							paste0("SELECT a.Column_name AS colName,\n",
									" a.Final_VarID AS varID\n",
								   " FROM fzzlRegrDataPrepMap AS a\n",
								   " WHERE a.AnalysisID = ",fquote(wideToDeepAnalysisId),
								   " AND a.Final_VarID IS NOT NULL \n",
									" ORDER BY a.Final_VarID\n"))

			vtemp <- vmapping[["varID"]]
			names(vtemp) <- vmapping[["colName"]]
			vmapping <- vtemp
			vallVars <- setdiff(vallVars,specID[["exclude"]])
		}
		else vmapping <- ""
	}
	else if(class(data@select)=="FLTableFunctionQuery")
	{
		#sqlstr <- paste0("CREATE VIEW ",getOption("ResultDatabaseFL"),
		#					".",deeptablename," AS ",constructSelect(data))
		#sqlSendUpdate(connection,sqlstr)
		deeptablename <- createView(pViewName=gen_view_name(""),
                                    pSelect=constructSelect(data))

		#sqlstr <- paste0("CREATE VIEW ",getOption("ResultDatabaseFL"),".",deeptablename1,
		#				" AS SELECT * FROM ",getOption("ResultDatabaseFL"),".",deeptablename,
		#				constructWhere(whereconditions))
		#t <- sqlSendUpdate(connection,sqlstr)
		deeptablename1<-createView(pViewName=gen_view_name("New"),
					pSelect=paste0("SELECT * FROM ",deeptablename,
										constructWhere(whereconditions)))


		deepx <- FLTable(deeptablename1,
                   "obs_id_colname",
                   "var_id_colname",
                   "cell_val_colname")
		deepx <- setAlias(setAlias,"")
		whereconditions <- ""
		vmapping <- colnames(deepx)
		names(vmapping) <- colnames(deepx)
	}
	else
	{
		deepx <- data
		data@select@whereconditions <- c(data@select@whereconditions,whereconditions)
		if(length(data@select@whereconditions)>0 &&
			data@select@whereconditions!=""){

			#sqlstr <- paste0("CREATE VIEW ",getOption("ResultDatabaseFL"),".",
			#				deeptablename," AS ",constructSelect(data))
			#t <- sqlSendUpdate(connection,sqlstr)
			deeptablename<-createView(pViewName=gen_view_name("New"),
                                      pSelect=constructSelect(data))			

			deepx <- FLTable(deeptablename,
	                   "obs_id_colname",
	                   "var_id_colname",
	                   "cell_val_colname")
			deepx <- setAlias(deepx,"")
		}
		whereconditions <- ""
		vmapping <- colnames(deepx)
		names(vmapping) <- colnames(deepx)
	}

	## Set RefLevel for Multinomial
	if(familytype=="multinomial"){
    	if(is.null(pRefLevel)){
    		pRefLevel <- sqlQuery(getFLConnection(),
    							paste0("SELECT cell_val_colname FROM (",
    									constructSelect(data),") a \n ",
    									"WHERE obs_id_colname = 1 \n AND ",
    									" var_id_colname = -1 \n "))[1,1]
    	}
    	pThreshold <- pRefLevel
    }

	vinclude <- NULL
	vexclude <- NULL
	##Insert SpecID
	vspecID <- "NULL"
	if(is.list(specID) && length(specID)>0 
		&& direction %in% c("UFbackward","Fbackward","backward"))
	{
		vspecID <- genRandVarName()
		vdf <- NULL
		vspecIDTable <- getRemoteTableName(tableName=ifelse(familytype=="linear","fzzlLinRegrModelVarSpec",
                                                            "fzzlLogRegrModelVarSpec"),temporaryTable=FALSE)
		if(!is.null(specID[["include"]]))
		{
			#browser()
			vinclude <- vmapping[charmatch(specID[["include"]],names(vmapping))]
			vinclude <- vinclude[!is.na(vinclude)]
			if(is.null(vinclude) || length(vinclude) < 1)
			stop("columns in lower are not in deeptable.",
				" Might be due to variable reduction during data preparation")
			# sqlstr <- c(sqlstr,paste0("INSERT INTO ", vspecIDTable," VALUES(",fquote(vspecID),",",
			# 				vinclude,",","'I')"))
            vdf <- rbind(vdf,data.frame(vspecID,vinclude,"I"))
		}
		if(!is.null(specID[["exclude"]]))
		{
			vexclude <- vmapping[charmatch(specID[["exclude"]],names(vmapping))]
			vexclude <- vexclude[!is.na(vexclude)]
			if(length(vexclude)>0 && vexclude!="")
			# sqlstr <- c(sqlstr,paste0("INSERT INTO ",vspecIDTable," VALUES(",fquote(vspecID),",",
			# 				vexclude,",","'X')"))
            vdf <- rbind(vdf,data.frame(vspecID,vexclude,"X"))
		}
		if(!is.null(vdf))
            t <- insertIntotbl(pTableName=vspecIDTable,
                                pValues=vdf)
  #                   t <- sqlSendUpdate(getFLConnection(),paste0(sqlstr,collapse=";"))
	}

    result <- list(deepx=deepx,
                   wideTable=data, ## todo: in case a deep table was passed this is not a wideTable
                   wideToDeepAnalysisId=wideToDeepAnalysisId,
                   formula=formula,
                   vmapping=vmapping,
                   mapTable=mapTable,
                   vspecID=vspecID,
                   highestpAllow1=highestpAllow1,
                   highestpAllow2=highestpAllow2,
                   topN=topN,
                   vexclude=vexclude,
                   vallVars=vallVars,
                   stepWiseDecrease=stepWiseDecrease,
                   eventweight=eventweight,
                   noneventweight=noneventweight,
                   maxiter=maxiter,
                   pThreshold=pThreshold,
                   offset=offset,
                   RegrDataPrepSpecs=vRegrDataPrepSpecs)
    class(result) <- "FLpreparedData"
	return(result)
}

#' @export
prepareData <- prepareData.lmGeneric


## move to file lm.R
#' @export
`$.FLLinRegr`<-function(object,property){
	#parentObject <- deparse(substitute(object))
	parentObject <- unlist(strsplit(unlist(strsplit(as.character(sys.call()),"(",fixed=T))[2],",",fixed=T))[1]
	if(property=="coefficients"){
		coefficientsvector <- coefficients(object)
		assign(parentObject,object,envir=parent.frame())
		return(coefficientsvector)
	}
	else if (property=="residuals"){
		residualsvector <- residuals(object)
		assign(parentObject,object,envir=parent.frame())
		return(residualsvector)
	}
	else if(property=="fitted.values")
	{
		fitvector <- fitted.values.FLGAM(object)
		assign(parentObject,object,envir=parent.frame())
		return(fitvector)
	}
	else if(property=="FLCoeffStdErr")
	{
		coeffVector <- coefficients(object)
		assign(parentObject,object,envir=parent.frame())
		return(object@results[["FLCoeffStdErr"]])
	}
	else if(property=="FLCoeffTStat")
	{
		coeffVector <- coefficients(object)
		assign(parentObject,object,envir=parent.frame())
		return(object@results[["FLCoeffTStat"]])
	}
	else if(property=="FLCoeffPValue")
	{
		coeffVector <- coefficients(object)
		assign(parentObject,object,envir=parent.frame())
		return(object@results[["FLCoeffPValue"]])
	}
	else if(property=="FLCoeffNonZeroDensity")
	{
		coeffVector <- coefficients(object)
		assign(parentObject,object,envir=parent.frame())
		return(object@results[["FLCoeffNonZeroDensity"]])
	}
	else if(property=="FLCoeffCorrelWithRes")
	{
		coeffVector <- coefficients(object)
		assign(parentObject,object,envir=parent.frame())
		return(object@results[["FLCoeffCorrelWithRes"]])
	}
	else if(property=="call")
	{
		return(object@results[["call"]])
	}
	else if(property=="FLLinRegrStats")
	{
		if(!is.null(object@results[["FLLinRegrStats"]]))
		return(object@results[["FLLinRegrStats"]])
		else
		{
			sqlstr <- paste0("SELECT * FROM fzzlLinRegrStats\n",
							" WHERE AnalysisID=",fquote(object@AnalysisID),
							" \nAND ModelID=",object@results[["modelID"]])

			statsdataframe <- sqlQuery(getFLConnection(),sqlstr)
			object@results <- c(object@results,list(FLLinRegrStats=statsdataframe))
			assign(parentObject,object,envir=parent.frame())
			return(statsdataframe)
		}
	}
	else if(property=="df.residual")
	{
		statsdataframe <- object$FLLinRegrStats
		colnames(statsdataframe) <- toupper(colnames(statsdataframe))
		dfResidualVector <- statsdataframe[["DFRESIDUAL"]]
		object@results <- c(object@results,list(df.residual=dfResidualVector))
		assign(parentObject,object,envir=parent.frame())
		return(dfResidualVector)
	}
	else if(property=="model")
	{
		## The Column order may not be same as
		## in formula object because add. columns
		## may be added by categorical trans.
			##This might stop any parent script!!
			##Need something that has wait time and
			## Default value.
			modelframe <- model.FLLinRegr(object)
			## Do not store. Better to fetch each time as
			## it saves memory and not much time loss in
			## Fetching.
			##object@results <- c(object@results,list(model=modelframe))
			assign(parentObject,object,envir=parent.frame())
			return(modelframe)
	}
	else if(property=="x")
	{
		if(!is.null(object@results[["x"]]))
		return(object@results[["x"]])
		
		modelframe <- getXMatrix(object,
								pDropCols=c(-1))
		object@results <- c(object@results,list(x=modelframe))
		assign(parentObject,object,envir=parent.frame())
		return(modelframe)
	}
	else if(property=="y")
	{
		##This is safer from simple subsetting of
		## WideTable as whereConditions may exist
		if(!is.null(object@results[["y"]]))
		return(object@results[["y"]])
		else
		{
			vtablename <- object@deeptable@select@table_name
			obs_id_colname <- getVariables(object@deeptable)[["obs_id_colname"]]
			var_id_colname <- getVariables(object@deeptable)[["var_id_colname"]]
			cell_val_colname <- getVariables(object@deeptable)[["cell_val_colname"]]

			sqlstr <- paste0("SELECT '%insertIDhere%' AS vectorIdColumn,\n",
								obs_id_colname," AS vectorIndexColumn,\n",
								cell_val_colname," AS vectorValueColumn\n",
							" FROM ",vtablename,
							" \nWHERE ",var_id_colname," = -1 \n")

			tblfunqueryobj <- new("FLTableFunctionQuery",
	                        connectionName = getFLConnectionName(),
	                        variables = list(
				                obs_id_colname = "vectorIndexColumn",
				                cell_val_colname = "vectorValueColumn"),
	                        whereconditions="",
	                        order = "",
	                        SQLquery=sqlstr)

			yvector <- newFLVector(
							select = tblfunqueryobj,
							Dimnames = list(object@deeptable@Dimnames[[1]],
											"vectorValueColumn"),
                            dims = as.integer(c(nrow(object@deeptable),1)),
							isDeep = FALSE)
			object@results <- c(object@results,list(y=yvector))
			assign(parentObject,object,envir=parent.frame())
			return(yvector)
		}
	}
	else if(property=="qr" || property=="rank")
	{
		if(!is.null(object@results[["qr"]]))
		{
			if(property=="qr")
			return(object@results[["qr"]])
			else if(property=="rank") 
			return(object@results[["qr"]]$rank)
		}
		else
		{
			modelmatrix <- object$x
			if(nrow(modelmatrix)>700 
				|| ncol(modelmatrix)>700)
			modelmatrix <- as.matrix(modelmatrix)
			# modelmatrix <- as.matrix(object$x)
			# qrList <- base::qr(modelmatrix)
			qrList <- qr(modelmatrix)
			vrank <- qrList$rank
			object@results <- c(object@results,list(qr=qrList))
			assign(parentObject,object,envir=parent.frame())
			if(property=="qr")
			return(qrList)
			else if(property=="rank") return(vrank)
		}
	}
	else if(property=="terms")
	{
		if(!is.null(object@results[["terms"]]))
		return(object@results[["terms"]])
		else
		{
			coeffVector <- object$coefficients
			vallVars <- all.vars(object@formula)
			vcolnames <- object@results[["modelColnames"]][-1]
			if(is.null(vcolnames))
				vcolnames <- names(coeffVector)[2:length(coeffVector)]
			vterms <- terms(formula(paste0(vallVars[1],"~",
				paste0(vcolnames,collapse="+"))))
			object@results <- c(object@results,list(terms=vterms))
			assign(parentObject,object,envir=parent.frame())
			return(vterms)
		}
	}
	else if(property=="xlevels")
	{
		cat("categorical variables are Transformed \n ")
		return(list())
	}
	else if(property=="assign")
	{
		return(c(0,rep(1,length(all.vars(object@formula))-1)))
	}

	else if(property=="formula")
	{
		if(!is.null(object@results[["formula"]]))
		return(object@results[["formula"]])
		else
		{
			coeffVector <- object$coefficients
			vallVars <- all.vars(object@formula)
			vcolnames <- object@results[["modelColnames"]][-1]
			if(is.null(vcolnames))
				vcolnames <- names(coeffVector)[2:length(coeffVector)]
			vterms <- terms(formula(paste0(vallVars[1],"~",
				paste0(vcolnames,collapse="+"))))
			object@results <- c(object@results,list(terms=vterms))
			assign(parentObject,object,envir=parent.frame())
			return(vterms)
		}
	}

	else if(property=="anova") stop("This feature is not available yet.")

	else stop("That's not a valid property \n ")
}

#' @export
coefficients<-function(table){
	UseMethod("coefficients",table)
}
#' @export
coefficients.default <- stats::coefficients

## move to file lm.R
#' @export
coefficients.FLLinRegr<-function(object){
	parentObject <- unlist(strsplit(unlist(strsplit(
		as.character(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
	if(is.FLTableMD(object@table))
		coeffVector <- coefficients.FLLinRegrMD(object)
	else 
	coeffVector <- coefficients.lmGeneric(object,
						FLCoeffStats=c(FLCoeffStdErr="STDERR",
							FLCoeffPValue="PVALUE",
							FLCoeffTStat="TSTAT",
							FLCoeffCorrelWithRes="CORRELWITHRES",
							FLCoeffNonZeroDensity="NONZERODENSITY"))
		assign(parentObject,object,envir=parent.frame())
	return(coeffVector)
}

## move to file lmGeneric.R
#' @export
coefficients.lmGeneric <-function(object,
								FLCoeffStats=c(),
								pIntercept=TRUE,
								...){
	if(!is.null(object@results[["coefficients"]]))
	return(object@results[["coefficients"]])
	else
	{
		##Since Currently only 1000 Columns are supported
		## by FLLinRegr, fetch them.
		#browser()
		# vmapping <- NULL
		vfcalls <- object@vfcalls
		vcoeffnames <- NULL
		vmodelnames <- NULL
		if(object@table@isDeep)
		coeffVector <- sqlQuery(getFLConnection(),
			paste0("SELECT * FROM ",vfcalls["coefftablename"],
				" where AnalysisID=",fquote(object@AnalysisID),
				ifelse(length(object@results[["modelID"]])>0,
					paste0(" AND ModelID=",object@results[["modelID"]]),""),
					" ORDER BY CoeffID"))
		else{
			#browser()
			vcoeffframe <- sqlQuery(getFLConnection(),
									paste0("SELECT a.*,b.* \n",
										   " FROM fzzlRegrDataPrepMap AS a, \n ",
										   vfcalls["coefftablename"]," AS b \n",
										   " WHERE a.Final_VarID = b.CoeffID \n",
											" AND a.AnalysisID = ",fquote(object@wideToDeepAnalysisId),
											"\n AND b.AnalysisID = ",fquote(object@AnalysisID),
											ifelse(length(object@results[["modelID"]])>0,
											paste0("\n AND b.ModelID = ",object@results[["modelID"]]),""),
											"\n ORDER BY CoeffID"))
			colnames(vcoeffframe) <- toupper(colnames(vcoeffframe))
			vcolumnnames <- unique(as.character(vcoeffframe[["COLUMN_NAME"]]))
			vcolumnnames <- vcolumnnames[2:length(vcolumnnames)]
			vmodelnames <- c(all.vars(object@formula)[1],
							vcolumnnames)
			coeffVector <- vcoeffframe
			vcolumnnames <- vcoeffframe[["COLUMN_NAME"]]
			vcolumnnames <- vcolumnnames[2:length(vcolumnnames)]
			want <- all.vars(object@formula)
			want <- want[2:length(want)]
			q <- unlist(sapply(want,
							function(x){
								which(vcolumnnames %in% x)}
						))+1
			coeffVector <- coeffVector[c(1,q), ]
			vcoeffnames <- as.vector(apply(coeffVector,1,
											function(x){
											  if(tolower(x["VAR_TYPE"])=="category")
											    return(paste0(x["COLUMN_NAME"],x["CATVALUE"]))
											  else return(x["COLUMN_NAME"])}))
			vmodelnames <- c(all.vars(object@formula)[1],
							unique(as.character(coeffVector[["COLUMN_NAME"]])[-1]))
		}

		colnames(coeffVector) <- toupper(colnames(coeffVector))
		coeffVector1 <- coeffVector[["COEFFVALUE"]]
		# vmapping <- as.FLVector(unique(c(-2,-1,coeffVector[["COEFFID"]])))
		if(!is.null(vcoeffnames)){
			if(!pIntercept)
				names(coeffVector1) <- as.character(vcoeffnames)
			else
				names(coeffVector1) <- c("(Intercept)",
										as.character(vcoeffnames)[2:length(vcoeffnames)])
		}
		else{
			vallVars <- all.vars(genDeepFormula(coeffVector[["COEFFID"]]))
			names(coeffVector1) <- c("(Intercept)",vallVars[2:length(vallVars)])
			if(!pIntercept)
				names(coeffVector1) <- vallVars
		}
		FLCoeffStats  <- lapply(FLCoeffStats,
								function(x){
									t<-coeffVector[[x]]
									names(t)<-names(coeffVector1)
									t
									})
		
		vcolnames <- colnames(object@deeptable)
		droppedCols <- vcolnames[!vcolnames %in% c("-1",coeffVector[["COEFFID"]])]
		object@results <- c(object@results,list(coefficients=coeffVector1,
												droppedCols=droppedCols),
												FLCoeffStats)
		object@results[["modelColnames"]]<-vmodelnames
        object@results[["CoeffID"]] <- as.numeric(coeffVector[["COEFFID"]])
		# object@results[["varIDMapping"]] <- vmapping
		parentObject <- unlist(strsplit(unlist(strsplit(
			as.character(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
		assign(parentObject,object,envir=parent.frame())
		return(coeffVector1)
	}
}

## move to file lm.R
#' @export
residuals.FLLinRegr<-function(object)
{
	if(!is.null(object@results[["residuals"]]))
	return(object@results[["residuals"]])
	else
	{
	    residualsvector <- calcResiduals(object=object)
		object@results <- c(object@results,list(residuals=residualsvector))
		parentObject <- unlist(strsplit(unlist(strsplit(
			as.character(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
		assign(parentObject,object,envir=parent.frame())
		return(residualsvector)
	}
}

## move to file lm.R
#' @export
model.FLLinRegr <- function(object,...)
{
	if(!is.null(object@results[["model"]]))
	return(object@results[["model"]])
	else
	{
		coeffVector <- object$coefficients
		vallVars <- all.vars(object@formula)
		vcolnames <- NULL
		if(!is.null(object@results[["modelColnames"]])){
			vcolnames <- object@results[["modelColnames"]]
			modelframe <- object@table
			modelframe@Dimnames[[2]] <- vcolnames
		}
		else{
			vdroppedCols <- object@results[["droppedCols"]]
			modelframe <- object@deeptable
			modelframe@select@whereconditions <- c(modelframe@select@whereconditions,
												paste0("var_id_colname NOT IN ",
														"(",paste0(c(0,-2,vdroppedCols),collapse=","),
														")"))

			if(is.matrix(coeffVector))
				vcolnames <- c(vallVars[1],
							colnames(coeffVector)[2:ncol(coeffVector)])
			else 
				vcolnames <- c(vallVars[1],
							names(coeffVector)[2:length(coeffVector)])
		}

		## Have to implement names for FLTable
		# modelframe@Dimnames <- list(modelframe@Dimnames[[1]],
		# 							vcolnames)
		# return(modelframe)
	
		modelframe <- as.data.frame(modelframe)
		if(!is.null(names(vcolnames)))
			colnames(modelframe) <- names(vcolnames)
		else colnames(modelframe) <- vcolnames
		
		object@results <- c(object@results,list(model=modelframe))
		parentObject <- unlist(strsplit(unlist(strsplit(
			as.character(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
		assign(parentObject,object,envir=parent.frame())
		return(modelframe)
	}
}

## move to file lm.R
#' @export
summary.FLLinRegr <- function(object,
                              calcResiduals=FALSE){
	if(is.FLTableMD(object@table))
		reqList <- summary.FLLinRegrMD(object)
	else{
		stat <- object$FLLinRegrStats
	  	coeffframe <- data.frame(object$coefficients,
	                           object$FLCoeffStdErr,
	                           object$FLCoeffTStat,
	                           object$FLCoeffPValue)
	  	colnames(coeffframe)<-c("Estimate","Std. Error","t value","Pr(>|t|)")

	  	#put rowname
	  	# rname <- all.vars(object@formula)
	  	# rownames(coeffframe) <- c(rownames(coeffframe)[1], rname[2:length(rname)])
        rownames(coeffframe) <- names(object$coefficients)

        if(calcResiduals)
            vresiduals <- as.vector(object$residuals)
        else vresiduals <- NULL
	  	reqList <- list(call = as.call(object@formula),
	                  residuals  = vresiduals,
	                  coefficients = as.matrix(coeffframe),
	                  sigma = stat$STDERR,
	                  df = as.vector(c((stat$DFREGRESSION + 1),stat$DFRESIDUAL, (stat$DFREGRESSION + 1))),
	                  r.squared = stat$RSQUARED,
	                  adj.r.squared = stat$ADJRSQUARED,
	                  fstatistic = c(stat$FSTAT, stat$DFREGRESSION, stat$DFRESIDUAL ),
	                  aliased = FALSE
	  				)
	  	class(reqList) <- "summary.lm"
	  	reqList
	}

  	parentObject <- unlist(strsplit(unlist(strsplit(as.character
							(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
	assign(parentObject,object,envir=parent.frame())
	return(reqList)
}




#' @export
predict<-function(object,newdata,...){
	UseMethod("predict",object)
}

## move to file lm.R
#' @export
predict.FLLinRegr <- function(object,
							newdata=object@table,
							scoreTable="",
                            ...){
	return(predict.lmGeneric(object,newdata=newdata,
							scoreTable=scoreTable,
                            ...))
}

## move to file lmGeneric.R
#' @export
predict.lmGeneric <- function(object,
							newdata=object@table,
							scoreTable="",
                            ...){
	if(!is.FLTable(newdata)) stop("scoring allowed on FLTable only")
	newdata <- setAlias(newdata,"")
	vinputTable <- newdata@select@table_name

	if(scoreTable=="")
	# scoreTable <- paste0(getOption("ResultDatabaseFL"),".",
	# 					gen_score_table_name(object@table@select@table_name))
	scoreTable <- gen_score_table_name(object@table@select@table_name)
	# else if(!grep(".",scoreTable)) 
	# 		scoreTable <- paste0(getOption("ResultDatabaseFL"),".",scoreTable)
	
	vfcalls <- object@vfcalls
	if(!newdata@isDeep)
	{
		newdataCopy <- newdata
        vRegrDataPrepSpecs <- setDefaultsRegrDataPrepSpecs(x=object@RegrDataPrepSpecs,
                                                            values=list(...))
		deepx <- FLRegrDataPrep(newdata,depCol=vRegrDataPrepSpecs$depCol,
								outDeepTableName=vRegrDataPrepSpecs$outDeepTableName,
								outObsIDCol=vRegrDataPrepSpecs$outObsIDCol,
								outVarIDCol=vRegrDataPrepSpecs$outVarIDCol,
								outValueCol=vRegrDataPrepSpecs$outValueCol,
								catToDummy=vRegrDataPrepSpecs$catToDummy,
								performNorm=vRegrDataPrepSpecs$performNorm,
								performVarReduc=vRegrDataPrepSpecs$performVarReduc,
								makeDataSparse=vRegrDataPrepSpecs$makeDataSparse,
								minStdDev=vRegrDataPrepSpecs$minStdDev,
								maxCorrel=vRegrDataPrepSpecs$maxCorrel,
								trainOrTest=1,
								excludeCols=vRegrDataPrepSpecs$excludeCols,
								classSpec=vRegrDataPrepSpecs$classSpec,
								whereconditions=vRegrDataPrepSpecs$whereconditions,
								inAnalysisID=object@wideToDeepAnalysisId)
		newdata <- deepx[["table"]]
		newdata <- setAlias(newdata,"")

		if(object@vfcalls["functionName"]=="FLPoissonRegr"){
			## Insert dependent and offset varids in deeptable
			vVaridCols <- c(-2)
			vcellValCols <- ifelse(object@offset!="",object@offset,0)

			# if(!all.vars(object@formula)[1] %in% colnames(newdataCopy))
			# 	stop("dependent column ",all.vars(object@formula)[1],
			# 		" not in newdata \n ")
			vVaridCols <- c(vVaridCols,-1)
			vcellValCols <- c(vcellValCols,all.vars(object@formula)[1])

			# vtablename <- newdataCopy@select@table_name
			vtablename <- table@select@table_name
			vtablename1 <- newdata@select@table_name

			vobsid <- getVariables(object@table)[["obs_id_colname"]]
			sqlstr <- paste0(" SELECT ",vobsid," AS obs_id_colname, \n ",
											vVaridCols," AS var_id_colname, \n ",
											vcellValCols," AS cell_val_colname \n  ",
							" FROM ",vtablename,collapse=" UNION ALL ")
			t <- insertIntotbl(pTableName=vtablename1,
                                pSelect=sqlstr)
			newdata@Dimnames[[2]] <- c("-1","-2",newdata@Dimnames[[2]])
		}
	}
	vtable <- newdata@select@table_name
	vobsid <- getVariables(newdata)[["obs_id_colname"]]
	vvarid <- getVariables(newdata)[["var_id_colname"]]
	vvalue <- getVariables(newdata)[["cell_val_colname"]]

	vinputCols <- list()
	vinputCols <- c(vinputCols,
					INPUT_TABLE=newdata@select@table_name,
					OBSID_COL=vobsid,
					VARID_COL=vvarid,
					VALUE_COL=vvalue
					)
	if(!object@vfcalls["functionName"]=="FLPoissonRegr")
	vinputCols <- c(vinputCols,
					WHERE_CLAUSE="NULL")
	vinputCols <- c(vinputCols,
					ANALYSISID=object@AnalysisID,
					OUTPUT_TABLE=scoreTable)

	if(!is.Hadoop())
	vinputCols <- c(vinputCols,
					NOTE=genNote(paste0("Scoring ",vfcalls["note"])))

	AnalysisID <- sqlStoredProc(getFLConnection(),
								vfcalls["scoretablename"],
								outputParameter=c(AnalysisID="a"),
								pInputParams=vinputCols)
	AnalysisID <- checkSqlQueryOutput(AnalysisID)

	sqlstr <- paste0(" SELECT '%insertIDhere%' AS vectorIdColumn,",
						vobsid," AS vectorIndexColumn,",
						vfcalls["valcolnamescoretable"]," AS vectorValueColumn",
					" FROM ",scoreTable)

	tblfunqueryobj <- new("FLTableFunctionQuery",
                        connectionName = getFLConnectionName(),
                        variables = list(
			                obs_id_colname = "vectorIndexColumn",
			                cell_val_colname = "vectorValueColumn"),
                        whereconditions="",
                        order = "",
                        SQLquery=sqlstr)

	flv <- newFLVector(
				select = tblfunqueryobj,
				Dimnames = list(rownames(newdata),
								"vectorValueColumn"),
                dims = as.integer(c(newdata@dims[1],1)),
				isDeep = FALSE)

	return(flv)
}

## move to file lm.R
NULL

#' Print FLLinRegr Object
#'
#' Printing of output from Linear Regression
#' 
#' @title Print FLLinRegr output Info
#' @method print FLLinRegr
#' @param object prints results of FLLinRegr on FL objects
#' @method coefficients FLLinRegr
#' @param object returns coefficient vector of the object
#' @method residuals FLLinRegr
#' @param object the residuals, that is response minus fitted values.
#' @method influence FLLinRegr
#' @param object returns the basic quantities which are used in forming a wide variety of diagnostics for checking the quality of regression fits.
#' @method lm.influence FLLinRegr
#' @param object returns the basic quantities which are used in forming a wide variety of diagnostics for checking the quality of regression fits.
#' @method plot FLLinRegr
#' @param object plots the results of FLLinRegr on FL objects.
#' @method summary FLLinRegr
#' @method predict FLLinRegr
#' @export
print.FLLinRegr<-function(object){
	parentObject <- unlist(strsplit(unlist(strsplit(
		as.character(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
	reqList <- list(call=object$call,
					coefficients=object$coefficients)

	class(reqList) <- "lm"
	assign(parentObject,object,envir=parent.frame())
	print(reqList)
}

## move to file lm.R
#' @export
setMethod("show","FLLinRegr",print.FLLinRegr)

## move to file lm.R
#' @export
plot.FLLinRegr <- function(object,method="R",...)
{
    parentObject <- unlist(strsplit(unlist(strsplit(
                        as.character(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
    if(method=="R"){
        vqr <- object$qr
        vqr <- list(qr=as.matrix(vqr$qr),
                    rank=as.integer(as.vector(vqr$rank)),
                    qraux=as.numeric(as.vector(vqr$qraux)),
                    pivot=as.integer(as.vector(vqr$pivot)))

        class(vqr)<-"qr"
        reqList <- list(residuals=as.vector(object$residuals),
                        coefficients=object$coefficients,
                        df.residual=object$df.residual,
                        qr=vqr,
                        rank=vqr$rank,
                        call=object$call,
                        xlevels=object$xlevels,
                        model=object$model,
                        terms=object$terms)
        class(reqList) <- "lm"
        assign(parentObject,object,envir=parent.frame())
        plot(reqList,...)
    }
    else{
        vfit <- as.vector(object$fitted.values)
        vresid <- as.vector(object$residuals)
        vactual <- sqlQuery(getFLConnection(),
                        paste0("SELECT ",getVariables(object@deeptable)[["cell_val_colname"]],
                                " FROM (",constructSelect(object@deeptable),") a ",
                                " WHERE a.",getVariables(object@deeptable)[["var_id_colname"]]," = -1 ",
                                " ORDER BY ",getVariables(object@deeptable)[["obs_id_colname"]]
                                ))[[1]]
        assign(parentObject,object,envir=parent.frame())
        plot(vfit,vresid,xlab="fitted.values",ylab="residuals",main="residual plot")
        plot(vactual,vfit,xlab="actual values",ylab="fitted.values",main="Actual vs Fitted")
    }
}

## move to file lm.R
#' @export
influence.FLLinRegr <- function(model,...){
	reqList <- list(residuals=as.vector(model$residuals),
					coefficients=model$coefficients,
					df.residual=model$df.residual,
					qr=model$qr,
					rank=model$rank,
					call=model$call,
					xlevels=model$xlevels,
					model=model$model,
					termsz=model$terms)
	class(reqList) <- "lm"
	parentObject <- unlist(strsplit(unlist(strsplit(as.character
		(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
	assign(parentObject,model,envir=parent.frame())
	return(stats::influence(reqList,...))
}

#' @export
lm.influence <- function(model,do.coef=TRUE,...){
	UseMethod("lm.influence",model)
}
#' @export
lm.influence.default <- stats::lm.influence
#' @export

## move to file lm.R
lm.influence.FLLinRegr <- function(model,do.coef=TRUE,...){
	reqList <- list(residuals=as.vector(model$residuals),
					coefficients=model$coefficients,
					df.residual=model$df.residual,
					qr=model$qr,
					rank=model$rank,
					call=model$call,
					xlevels=model$xlevels,
					model=model$model,
					terms=model$terms)
	class(reqList) <- "lm"
	parentObject <- unlist(strsplit(unlist(strsplit(as.character
		(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
	assign(parentObject,model,envir=parent.frame())
	return(stats::lm.influence(reqList,do.coef,...))
}

##Return list of coefficients vectors
coefficients.FLLinRegrMD <- function(object){
	if(!is.null(object@results[["coefficients"]]))
	return(object@results[["coefficients"]])
	else
	{
		if(object@table@isDeep){
			coeffVector <- sqlQuery(getFLConnection(),
								paste0("SELECT * FROM ",object@vfcalls["coefftablename"],
										" where AnalysisID=",fquote(object@AnalysisID),
										" AND ModelID IN(",paste0(object@deeptable@Dimnames[[3]],collapse=","),
										") ORDER BY ModelID,CoeffID"))
			vcoeffnames <- as.vector(apply(coeffVector,1,
										function(x){
											if(as.numeric(x[["COEFFID"]])=="0")
												return("(Intercept)")
											else return(paste0("Var",x[["COEFFID"]]))
										}))
		}
		else{
			vcoeffframe <- sqlQuery(getFLConnection(),
									paste0("SELECT a.*,b.* \n",
										   " FROM fzzlRegrDataPrepMDMap AS a, \n ",
										   object@vfcalls["coefftablename"]," AS b \n",
										   " WHERE a.Final_VarID = b.CoeffID \n",
											" AND a.AnalysisID = ",fquote(object@wideToDeepAnalysisId),
											"\n AND b.AnalysisID = ",fquote(object@AnalysisID),
											"\n AND a.groupID = b.modelID ",
											"\n AND b.ModelID IN(",
												paste0(object@deeptable@Dimnames[[3]],
													collapse=","),
											")\n ORDER BY ModelID,CoeffID"))
			colnames(vcoeffframe) <- toupper(colnames(vcoeffframe))
			want <- all.vars(object@formula)
			want <- want[2:length(want)]
			q <- dlply(vcoeffframe,"MODELID",function(x){
						c(1,unlist(sapply(want,
								function(y)
									which(
										as.character(x[["COLUMN_NAME"]][-1]) %in% y)
										))+1)
						})
			for(i in 2:length(q)){
				q[[i]] <- q[[i]]+length(q[[i-1]])
			}

			coeffVector <- vcoeffframe[unlist(q),]
			vcoeffnames <- as.vector(apply(coeffVector,1,
										function(x){
											if(x[["COLUMN_NAME"]]=="INTERCEPT")
												return("(Intercept)")
											else if(tolower(x["VAR_TYPE"])=="category")
												return(paste0(x["COLUMN_NAME"],x["CATVALUE"]))
											else return(x["COLUMN_NAME"])
										}))
		}

		coeffVector[["COEFFNAMES"]] <- vcoeffnames

		vcoeffList <- dlply(coeffVector,"MODELID",
							function(x){
								vcoeff <- x[["COEFFVALUE"]]
								names(vcoeff) <- x[["COEFFNAMES"]]
								return(vcoeff)
								})
		names(vcoeffList) <- paste0("Model",object@deeptable@Dimnames[[3]])
		parentObject <- unlist(strsplit(unlist(strsplit(as.character
							(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
		object@results[["coefficients"]] <- vcoeffList
		object@results[["coeffframe"]] <- coeffVector
		assign(parentObject,object,envir=parent.frame())
		return(vcoeffList)
	}
}

#' @export
summary.FLLinRegrMD <- function(object){
	vcoeffList <- object$coefficients
	coeffframe <- object@results[["coeffframe"]]
	if(is.null(object@results[["statsframe"]]))
		statsframe <- sqlQuery(getFLConnection(),
						paste0("SELECT * FROM ",object@vfcalls["statstablename"],
								" WHERE AnalysisID=",fquote(object@AnalysisID),
								" ORDER BY MODELID "))
	else statsframe <- object@results[["statsframe"]]
	colnames(statsframe) <- toupper(colnames(statsframe))
	vresList <- lapply(object@deeptable@Dimnames[[3]],
					function(x){
						vtemp <- coeffframe[coeffframe[,"MODELID"]==x,]
						vrownames <- vtemp[["COEFFNAMES"]]
						vtemp <- vtemp[,c("COEFFVALUE","STDERR","TSTAT","PVALUE","NONZERODENSITY","CORRELWITHRES")]
						vcoeffmat <- as.matrix(vtemp)
						rownames(vcoeffmat) <- vrownames
						colnames(vcoeffmat) <- c("Estimate","Std.Err","t-stat",
												"p-value","non-zero Density","Correl With Residual")
						vtemp <- statsframe[statsframe[,"MODELID"]==x,]
						vsummaryList <- list(coeffframe=vcoeffmat,
											statsframe=vtemp,
											call=object$call)
						class(vsummaryList) <- "summary.FLLinRegrMD"
						return(vsummaryList)
						})
	names(vresList) <- paste0("Model",object@deeptable@Dimnames[[3]])
	parentObject <- unlist(strsplit(unlist(strsplit(as.character
							(sys.call()),"(",fixed=T))[2],")",fixed=T))[1]
	object@results[["statsframe"]] <- statsframe
	assign(parentObject,object,envir=parent.frame())
	return(vresList)
}

#' @export
print.summary.FLLinRegrMD <- function(object){
	ret <- object$statsframe
	cat("Call:\n")
	cat(paste0(object$call),"\n")
	cat("\n\nCoefficients:\n")
	print(object$coeffframe)
	cat("\n---\n")
	cat("Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 '' 1\n")
	cat("Residual standard error: ",ret[["MSRESIDUAL"]]," on ",ret[["DFRESIDUAL"]]," degrees of freedom\n\n")
	cat("Multiple R-squared: ",ret[["RSQUARED"]]," , Adjusted R-squared: ",ret[["ADJRSQUARED"]],"\n")
	FStatPVal<-pf(ret[["FSTAT"]],ret[["DFREGRESSION"]],ret[["DFRESIDUAL"]],lower.tail=FALSE)
	cat("F-statistic: ",ret[["FSTAT"]]," on ",ret[["DFREGRESSION"]]," and ",ret[["DFRESIDUAL"]]
		,"DF , p-value: ",FStatPVal,"\n")
	cat("MSRegression: ",ret[["MSREGRESSION"]]," , SigFStat: ",ret[["SIGFSTAT"]],"\n")
	cat("DWStat: ",ret[["DWSTAT"]]," , ResidualAutoCorrel: ",ret[["RESIDUALAUTOCORREL"]],"\n")
	cat("BPStat: ",ret[["BPSTAT"]]," , SigBPStat: ",ret[["SIGBPSTAT"]],"\n")
}

#' @export
`[[.FLLinRegr`<-function(object,property){
    #parentObject <- deparse(substitute(object))
    parentObject <- unlist(strsplit(unlist(strsplit(as.character(sys.call()),
                        "(",fixed=T))[2],",",fixed=T))[1]
    vresult <- `$.FLLinRegr`(object=object,property=property)
    assign(parentObject,object,envir=parent.frame())
    return(vresult)
    
}
setDefaultsRegrDataPrepSpecs <- function(x,values){
    x <- as.list(x)
    for(i in c("catToDummy","performNorm",
                "performVarReduc","minStdDev",
                "maxCorrel","makeDataSparse",
                "excludeCols","classSpec")){
        if(i %in% names(values))
            x[[i]] <- values
        else if(is.null(x[[i]])){
            if(i %in% c("maxCorrel","makeDataSparse"))
                x[[i]] <- 1
            else if(i %in% c("excludeCols","depCol",
                            "outDeepTableName","outObsIDCol",
                            "outVarIDCol","outValueCol",
                            "whereconditions"))
                x[[i]] <- ""
            else if(i %in% "classSpec")
                x[[i]] <- list()
            else x[[i]] <- 0
        }
    }
    x[["depCol"]] <- ""
    x
}
