storedProcMappingsFL <-
structure(list(FLRegrDataPrep.TDAster = structure(list(funcName = "FLRegrDataPrep", 
    platform = "TDAster", funcNamePlatform = "FLRegrDataPrep", 
    args = c("InWideTable", "ObsIDCol", "DepCol", "OutDeepTable", 
    "OutObsIDCol", "OutVarIDCol", "OutValueCol", "CatToDummy", 
    "PerformNorm", "PerformVarReduc", "MakeDataSparse", "MinStdDev", 
    "MaxCorrel", "TrainOrTest", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"), argsPlatform = structure(c("InWideTable", 
    "ObsIDCol", "DepCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "CatToDummy", "PerformNorm", "PerformVarReduc", 
    "MakeDataSparse", "MinStdDev", "MaxCorrel", "TrainOrTest", 
    "ExcludeCols", "ClassSpec", "WhereClause", "InAnalysisID"
    ), .Names = c("INPUT_TABLE", "OBSID_COL", "DEP_VAR_COL", 
    "OUTPUT_TABLE", "OUTPUT_OBSID_COL", "OUTPUT_VARID_COL", "OUTPUT_VALUE_COL", 
    "CAT_TO_DUMMY", "PERF_NORM", "PERF_VAR_REDUC", "MAKE_SPARSE", 
    "MIN_STDDEV", "MAX_CORREL", "TRAIN_OR_TEST", "EXCLUDE_COLS", 
    "CLASS_SPEC", "WHERE_CLAUSE", "ANALYSISID"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLRegrDataPrep.TD = structure(list(
    funcName = "FLRegrDataPrep", platform = "TD", funcNamePlatform = "FLRegrDataPrep", 
    args = c("InWideTable", "ObsIDCol", "DepCol", "OutDeepTable", 
    "OutObsIDCol", "OutVarIDCol", "OutValueCol", "CatToDummy", 
    "PerformNorm", "PerformVarReduc", "MakeDataSparse", "MinStdDev", 
    "MaxCorrel", "TrainOrTest", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"), argsPlatform = structure(c("InWideTable", 
    "ObsIDCol", "DepCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "CatToDummy", "PerformNorm", "PerformVarReduc", 
    "MakeDataSparse", "MinStdDev", "MaxCorrel", "TrainOrTest", 
    "ExcludeCols", "ClassSpec", "WhereClause", "InAnalysisID"
    ), .Names = c("InWideTable", "ObsIDCol", "DepCol", "OutDeepTable", 
    "OutObsIDCol", "OutVarIDCol", "OutValueCol", "CatToDummy", 
    "PerformNorm", "PerformVarReduc", "MakeDataSparse", "MinStdDev", 
    "MaxCorrel", "TrainOrTest", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLTrainDataPrep.Hadoop = structure(list(
    funcName = "FLTrainDataPrep", platform = "Hadoop", funcNamePlatform = "FLTrainDataPrep", 
    args = c("InWideTable", "ObsIDCol", "DepCol", "OutDeepTable", 
    "OutObsIDCol", "OutVarIDCol", "OutValueCol", "CatToDummy", 
    "PerformNorm", "PerformVarReduc", "MakeDataSparse", "MinStdDev", 
    "MaxCorrel", "ExcludeCols", "ClassSpec", "WhereClause", "InAnalysisID"
    ), argsPlatform = structure(c("InWideTable", "ObsIDCol", 
    "DepCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", "OutValueCol", 
    "CatToDummy", "PerformNorm", "PerformVarReduc", "MakeDataSparse", 
    "MinStdDev", "MaxCorrel", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"), .Names = c("InWideTable", "ObsIDCol", "DepCol", 
    "OutDeepTable", "OutObsIDCol", "OutVarIDCol", "OutValueCol", 
    "CatToDummy", "PerformNorm", "PerformVarReduc", "MakeDataSparse", 
    "MinStdDev", "MaxCorrel", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLTestDataPrep.Hadoop = structure(list(
    funcName = "FLTestDataPrep", platform = "Hadoop", funcNamePlatform = "FLTestDataPrep", 
    args = c("InWideTable", "ObsIDCol", "OutDeepTable", "OutObsIDCol", 
    "OutVarIDCol", "OutValueCol", "WhereClause", "MakeDataSparse", 
    "InAnalysisID"), argsPlatform = structure(c("InWideTable", 
    "ObsIDCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "WhereClause", "MakeDataSparse", "InAnalysisID"
    ), .Names = c("InWideTable", "ObsIDCol", "OutDeepTable", 
    "OutObsIDCol", "OutVarIDCol", "OutValueCol", "WhereClause", 
    "MakeDataSparse", "InAnalysisID"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLRegrDataPrepMD.TD = structure(list(
    funcName = "FLRegrDataPrepMD", platform = "TD", funcNamePlatform = "FLRegrDataPrepMD", 
    args = c("InWideTable", "GroupID", "ObsIDCol", "DepCol", 
    "OutDeepTable", "OutGroupIDCol", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "CatToDummy", "PerformNorm", "PerformVarReduc", 
    "MakeDataSparse", "MinStdDev", "MaxCorrel", "TrainOrTest", 
    "ExcludeCols", "ClassSpec", "WhereClause", "InAnalysisID"
    ), argsPlatform = structure(c("InWideTable", "GroupID", "ObsIDCol", 
    "DepCol", "OutDeepTable", "OutGroupIDCol", "OutObsIDCol", 
    "OutVarIDCol", "OutValueCol", "CatToDummy", "PerformNorm", 
    "PerformVarReduc", "MakeDataSparse", "MinStdDev", "MaxCorrel", 
    "TrainOrTest", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"), .Names = c("InWideTable", "GroupID", "ObsIDCol", 
    "DepCol", "OutDeepTable", "OutGroupIDCol", "OutObsIDCol", 
    "OutVarIDCol", "OutValueCol", "CatToDummy", "PerformNorm", 
    "PerformVarReduc", "MakeDataSparse", "MinStdDev", "MaxCorrel", 
    "TrainOrTest", "ExcludeCols", "ClassSpec", "WhereClause", 
    "InAnalysisID"))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLWideToDeep.TDAster = structure(list(
    funcName = "FLWideToDeep", platform = "TDAster", funcNamePlatform = "FLWideToDeep", 
    args = c("InWideTable", "ObsIDCol", "OutDeepTable", "OutObsIDCol", 
    "OutVarIDCol", "OutValueCol", "ExcludeCols", "ClassSpec", 
    "WhereClause"), argsPlatform = structure(c("InWideTable", 
    "ObsIDCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "ExcludeCols", "ClassSpec", "WhereClause"), .Names = c("INPUT_TABLE", 
    "OBSID_COL", "OUTPUT_TABLE", "OUTPUT_OBSID_COL", "OUTPUT_VARID_COL", 
    "OUTPUT_VALUE_COL", "EXCLUDE_COLS", "CLASS_SPEC", "WHERE_CLAUSE"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLWideToDeep.Hadoop = structure(list(
    funcName = "FLWideToDeep", platform = "Hadoop", funcNamePlatform = "FLWideToDeep", 
    args = c("InWideTable", "ObsIDCol", "OutDeepTable", "OutObsIDCol", 
    "OutVarIDCol", "OutValueCol", "MakeDataSparse", "ExcludeCols", 
    "ClassSpec", "WhereClause"), argsPlatform = structure(c("InWideTable", 
    "ObsIDCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "MakeDataSparse", "ExcludeCols", "ClassSpec", 
    "WhereClause"), .Names = c("InWideTable", "ObsIDCol", "OutDeepTable", 
    "OutObsIDCol", "OutVarIDCol", "OutValueCol", "MakeDataSparse", 
    "ExcludeCols", "ClassSpec", "WhereClause"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLWideToDeep.TD = structure(list(
    funcName = "FLWideToDeep", platform = "TD", funcNamePlatform = "FLWideToDeep", 
    args = c("InWideTable", "ObsIDCol", "OutDeepTable", "OutObsIDCol", 
    "OutVarIDCol", "OutValueCol", "ExcludeCols", "ClassSpec", 
    "WhereClause"), argsPlatform = structure(c("InWideTable", 
    "ObsIDCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "ExcludeCols", "ClassSpec", "WhereClause"), .Names = c("InWideTable", 
    "ObsIDCol", "OutDeepTable", "OutObsIDCol", "OutVarIDCol", 
    "OutValueCol", "ExcludeCols", "ClassSpec", "WhereClause"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLDeepToWide.TDAster = structure(list(
    funcName = "FLDeepToWide", platform = "TDAster", funcNamePlatform = "FLDeepToWide", 
    args = c("DeepTable", "ObsIDCol", "VarIDCol", "ValueCol", 
    "MapTable", "MapName", "WideTable"), argsPlatform = structure(c("DeepTable", 
    "ObsIDCol", "VarIDCol", "ValueCol", "MapTable", "MapName", 
    "WideTable"), .Names = c("INPUT_TABLE", "OBSID_COL", "VARID_COL", 
    "VALUE_COL", "MAP_TABLE", "MAP_NAME", "OUTPUT_TABLE"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), . = NULL, 
    FLKMeans.TDAster = structure(list(funcName = "FLKMeans", 
        platform = "TDAster", funcNamePlatform = "FLKMeans", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "Clusters", "Iterations", 
        "Hypothesis", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Hypothesis", "Note"), .Names = c("INPUT_TABLE", 
        "OBSID_COL", "VARID_COL", "VALUE_COL", "WHERE_CLAUSE", 
        "CLUSTERS", "MAX_ITER", "HYPOTHESIS", "NOTE"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLKMeans.TD = structure(list(funcName = "FLKMeans", platform = "TD", 
        funcNamePlatform = "FLKMeans", args = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Hypothesis", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Hypothesis", "Note"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Hypothesis", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLKMeans.Hadoop = structure(list(funcName = "FLKMeans", platform = "Hadoop", 
        funcNamePlatform = "FLKMeans", args = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Hypothesis", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Note"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "ClusterNumber", "MaxIteration", "Notes"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLKMedoids.TDAster = structure(list(funcName = "FLKMedoids", 
        platform = "TDAster", funcNamePlatform = "FLKMedoids", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "Medoids", "Iterations", 
        "DistTable", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Medoids", "Iterations", "Hypothesis", "Note"), .Names = c("INPUT_TABLE", 
        "OBSID_COL", "VARID_COL", "VALUE_COL", "WHERE_CLAUSE", 
        "MEDOIDS", "MAX_ITER", "INPUT_DIST_TABLE", "NOTE"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLKMedoids.TD = structure(list(funcName = "FLKMedoids", platform = "TD", 
        funcNamePlatform = "FLKMedoids", args = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Medoids", "Iterations", "DistTable", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Medoids", "Iterations", "DistTable", "Note"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Medoids", "Iterations", "DistTable", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLKMedoids.Hadoop = structure(list(funcName = "FLKMedoids", 
        platform = "Hadoop", funcNamePlatform = "FLKMedoids", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "Medoids", "Iterations", 
        "DistTable", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Medoids", "Iterations", "DistTable", "Note"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Medoids", "Iterations", "DistTable", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLFKMeans.TDAster = structure(list(funcName = "FLFKMeans", 
        platform = "TDAster", funcNamePlatform = "FLFKMeans", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "Clusters", "Iterations", 
        "Fuzzy", "Hypothesis", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Fuzzy", "Hypothesis", "Note"
        ), .Names = c("INPUT_TABLE", "OBSID_COL", "VARID_COL", 
        "VALUE_COL", "WHERE_CLAUSE", "CLUSTERS", "MAX_ITER", 
        "FUZZY", "HYPOTHESIS", "NOTE"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLHKMeans.TDAster = structure(list(funcName = "FLHKMeans", 
        platform = "TDAster", funcNamePlatform = "FLHKMeans", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "Levels", "Clusters", 
        "Iterations", "Hypothesis", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "Levels", 
        "WhereClause", "Clusters", "Iterations", "Hypothesis", 
        "Note"), .Names = c("INPUT_TABLE", "OBSID_COL", "VARID_COL", 
        "VALUE_COL", "LEVELS", "WHERE_CLAUSE", "CLUSTERS", "MAX_ITER", 
        "HYPOTHESIS", "NOTE"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), FLHKMeans.Hadoop = structure(list(
        funcName = "FLHKMeans", platform = "Hadoop", funcNamePlatform = "FLKMeans", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "Levels", "Clusters", 
        "Iterations", "Hypothesis", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "Clusters", "Iterations", "Note"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "ClusterNumber", "MaxIteration", "Notes"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLLinRegr.Hadoop = structure(list(funcName = "FLLinRegr", 
        platform = "Hadoop", funcNamePlatform = "FLLinRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "Note"), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "Note"), .Names = c("TableName", 
        "ObsIDCol", "VarIDCol", "ValCol", "Notes"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLLinRegr.TD = structure(list(funcName = "FLLinRegr", platform = "TD", 
        funcNamePlatform = "FLLinRegr", args = c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "Note"), .Names = c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLLinRegr.TDAster = structure(list(funcName = "FLLinRegr", 
        platform = "TDAster", funcNamePlatform = "FLLinRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "Note"), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "Note"), .Names = c("INPUT_TABLE", 
        "OBSID_COL", "VARID_COL", "VALUE_COL", "NOTE"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLLinRegrMultiDataSet.TD = structure(list(funcName = "FLLinRegrMultiDataSet", 
        platform = "TD", funcNamePlatform = "FLLinRegrMultiDataSet", 
        args = c("TableName", "GroupIDCol", "ObsIDCol", "VarIDCol", 
        "ValueCol", "Note"), argsPlatform = structure(c("TableName", 
        "GroupIDCol", "ObsIDCol", "VarIDCol", "ValueCol", "Note"
        ), .Names = c("TableName", "GroupIDCol", "ObsIDCol", 
        "VarIDCol", "ValueCol", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLLinRegrMultiDataSet.Hadoop = structure(list(funcName = "FLLinRegrMultiDataSet", 
        platform = "Hadoop", funcNamePlatform = "FLLinRegrMultiDataSet", 
        args = c("TableName", "GroupIDCol", "ObsIDCol", "VarIDCol", 
        "ValueCol", "Note"), argsPlatform = structure(c("TableName", 
        "GroupIDCol", "ObsIDCol", "VarIDCol", "ValueCol", "Note"
        ), .Names = c("TableName", "GroupIDCol", "ObsIDCol", 
        "VarIDCol", "ValueCol", "Notes"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLLinRegrScore.TD = structure(list(funcName = "FLLinRegrScore", 
        platform = "TD", funcNamePlatform = "FLLinRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "WhereClause", "RegrAnalysisID", "ScoreTable", "Note"
        ), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValCol", "WhereClause", "RegrAnalysisID", 
        "ScoreTable", "Note"), .Names = c("TableName", "ObsIDCol", 
        "VarIDCol", "ValCol", "WhereClause", "RegrAnalysisID", 
        "ScoreTable", "Note"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), FLLinRegrScore.TDAster = structure(list(
        funcName = "FLLinRegrScore", platform = "TDAster", funcNamePlatform = "FLLinRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "WhereClause", "RegrAnalysisID", "ScoreTable", "Note"
        ), argsPlatform = structure(c("RegrAnalysisID", "TableName", 
        "ObsIDCol", "VarIDCol", "ValCol", "ScoreTable", "WhereClause", 
        "Note"), .Names = c("ANALYSISID", "INPUT_TABLE", "OBSID_COL", 
        "VARID_COL", "VALUE_COL", "OUTPUT_TABLE", "WHERE_CLAUSE", 
        "NOTE"))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLLinRegrScore.Hadoop = structure(list(
        funcName = "FLLinRegrScore", platform = "Hadoop", funcNamePlatform = "FLLinRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "WhereClause", "RegrAnalysisID", "ScoreTable", "Note"
        ), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValCol", "WhereClause", "RegrAnalysisID", 
        "ScoreTable"), .Names = c("TableName", "ObsIDCol", "VarIDCol", 
        "ValCol", "WhereClause", "RegrAnalysisID", "ScoreTable"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLLogRegr.Hadoop = structure(list(
        funcName = "FLLogRegr", platform = "Hadoop", funcNamePlatform = "FLLogRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "MaxIterations", "pThreshold", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "pThreshold", "Note"), .Names = c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "MaxIterations", "pThreshold", 
        "Notes"))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLLogRegr.TD = structure(list(funcName = "FLLogRegr", 
        platform = "TD", funcNamePlatform = "FLLogRegr", args = c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "pThreshold", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "pThreshold", "Note"), .Names = c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "MaxIterations", "pThreshold", 
        "Note"))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLLogRegr.TDAster = structure(list(
        funcName = "FLLogRegr", platform = "TDAster", funcNamePlatform = "FLLogRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "Note"), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "MaxIterations", "pThreshold", 
        "Note"), .Names = c("INPUT_TABLE", "OBSID_COL", "VARID_COL", 
        "VALUE_COL", "MAX_ITER", "THRESHOLD", "NOTE"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLLogRegrMultiDataSet.TD = structure(list(funcName = "FLLogRegrMultiDataSet", 
        platform = "TD", funcNamePlatform = "FLLogRegrMultiDataSet", 
        args = c("TableName", "GroupIDCol", "ObsIDCol", "VarIDCol", 
        "ValueCol", "MaxIterations", "pThreshold", "Note"), argsPlatform = structure(c("TableName", 
        "GroupIDCol", "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "pThreshold", "Note"), .Names = c("TableName", "GroupIDCol", 
        "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "pThreshold", "Note"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), . = NULL, FLLogRegrScore.TD = structure(list(
        funcName = "FLLogRegrScore", platform = "TD", funcNamePlatform = "FLLogRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "WhereClause", "RegrAnalysisID", "ScoreTable", "Note"
        ), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValCol", "WhereClause", "RegrAnalysisID", 
        "ScoreTable", "Note"), .Names = c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "WhereClause", "RegrAnalysisID", 
        "ScoreTable", "Note"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), FLLogRegrScore.TDAster = structure(list(
        funcName = "FLLogRegrScore", platform = "TDAster", funcNamePlatform = "FLLogRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "WhereClause", "RegrAnalysisID", "ScoreTable", "Note"
        ), argsPlatform = structure(c("RegrAnalysisID", "TableName", 
        "ObsIDCol", "VarIDCol", "ValCol", "WhereClause", "ScoreTable", 
        "Note"), .Names = c("ANALYSISID", "INPUT_TABLE", "OBSID_COL", 
        "VARID_COL", "VALUE_COL", "WHERE_CLAUSE", "OUTPUT_TABLE", 
        "NOTE"))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLLogRegrScore.Hadoop = structure(list(
        funcName = "FLLogRegrScore", platform = "Hadoop", funcNamePlatform = "FLLogRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "WhereClause", "RegrAnalysisID", "ScoreTable", "Note"
        ), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValCol", "WhereClause", "RegrAnalysisID", 
        "ScoreTable"), .Names = c("TableName", "ObsIDCol", "VarIDCol", 
        "ValueCol", "WhereClause", "RegrAnalysisID", "ScoreTable"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLPoissonRegr.Hadoop = structure(list(
        funcName = "FLPoissonRegr", platform = "Hadoop", funcNamePlatform = "FLPoissonRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "MaxIterations", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "Note"), .Names = c("TableName", "ObsIDCol", "VarIDCol", 
        "ValueCol", "MaxIterations", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLPoissonRegr.TD = structure(list(funcName = "FLPoissonRegr", 
        platform = "TD", funcNamePlatform = "FLPoissonRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "MaxIterations", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDCol", "VarIDCol", "ValueCol", "MaxIterations", 
        "Note"), .Names = c("TableName", "ObsIDCol", "VarIDCol", 
        "ValueCol", "MaxIterations", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLPoissonRegr.TDAster = structure(list(funcName = "FLPoissonRegr", 
        platform = "TDAster", funcNamePlatform = "FLPoissonRegr", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValueCol", 
        "Note"), argsPlatform = structure(c("TableName", "ObsIDCol", 
        "VarIDCol", "ValueCol", "MaxIterations", "Note"), .Names = c("INPUT_TABLE", 
        "OBSID_COL", "VARID_COL", "VALUE_COL", "MAX_ITER", "NOTE"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLPoissonRegrScore.TD = structure(list(
        funcName = "FLPoissonRegrScore", platform = "TD", funcNamePlatform = "FLPoissonRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "RegrAnalysisID", "ScoreTable", "Note"), argsPlatform = structure(c("TableName", 
        "ObsIDCol", "VarIDCol", "ValCol", "RegrAnalysisID", "ScoreTable", 
        "Note"), .Names = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "AnalysisID", "ScoreTable", "Note"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLPoissonRegrScore.TDAster = structure(list(funcName = "FLPoissonRegrScore", 
        platform = "TDAster", funcNamePlatform = "FLPoissonRegrScore", 
        args = c("TableName", "ObsIDCol", "VarIDCol", "ValCol", 
        "RegrAnalysisID", "ScoreTable", "Note"), argsPlatform = structure(c("Table", 
        "ObsIDCol", "VarIDCol", "ValCol", "RegrAnalysisID", "ScoreTable", 
        "Note"), .Names = c("INPUT_TABLE", "OBSID_COL", "VARID_COL", 
        "VALUE_COL", "ANALYSISID", "OUTPUT_TABLE", "NOTE"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLVarCluster.TD = structure(list(funcName = "FLVarCluster", 
        platform = "TD", funcNamePlatform = "FLVarCluster", args = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "GroupBy", "MatrixType", "Contrib", "TableOutput"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "GroupBy", "MatrixType", "Contrib", "TableOutput"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "GroupBy", "MatrixType", "Contrib", "TableOutput"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLVarCluster.Hadoop = structure(list(funcName = "FLVarCluster", 
        platform = "Hadoop", funcNamePlatform = "FLVarCluster", 
        args = c("TableName", "ObsIDColName", "VarIDColName", 
        "ValueColName", "WhereClause", "GroupBy", "MatrixType", 
        "Contrib", "TableOutput"), argsPlatform = structure(c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "GroupBy", "MatrixType", "Contrib", "TableOutput"), .Names = c("TableName", 
        "ObsIDColName", "VarIDColName", "ValueColName", "WhereClause", 
        "GroupBy", "MatrixType", "Contrib", "TableOutput"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, FLSystemTables.Hadoop = structure(list(funcName = "FLSystemTables", 
        platform = "Hadoop", funcNamePlatform = "FLSystemTables", 
        args = "fzzlRegrDataPrepMap", argsPlatform = structure("fzzlRegrDataPrepMap", .Names = "fzzlDataPrepMap")), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLSystemTables.TD = structure(list(funcName = "FLSystemTables", 
        platform = "TD", funcNamePlatform = "FLSystemTables", 
        args = "fzzlRegrDataPrepMap", argsPlatform = structure("fzzlRegrDataPrepMap", .Names = "fzzlRegrDataPrepMap")), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    . = NULL, RANDOM.Hadoop = structure(list(funcName = "RANDOM", 
        platform = "Hadoop", funcNamePlatform = "RAND", args = character(0), 
        argsPlatform = structure("pArg2", .Names = "pArg2")), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    RANDOM.TD = structure(list(funcName = "RANDOM", platform = "TD", 
        funcNamePlatform = "RANDOM", args = character(0), argsPlatform = structure(c("pArg1", 
        "pArg2"), .Names = c("pArg1", "pArg2"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    prefix.TD = "CALL ", prefix.TDAster = "SELECT * FROM ", prefix.Hadoop = "SELECT ", 
    preArgs.TD = "", preArgs.TDAster = "ON (SELECT 1 ) PARTITION BY 1 \n", 
    preArgs.Hadoop = "", extraPars.TDAster = structure("NULL", .Names = "DSN"), 
    withOutputPars.TD = TRUE, withOutputPars.TDAster = FALSE, 
    withOutputPars.Hadoop = FALSE, withArgNames.TD = "none", 
    withArgNames.TDAster = "()", argSeparator.TDAster = "\n", 
    withArgNames.Hadoop = "none", includeWhere.Hadoop = FALSE, 
    includeWhere.TDAster = TRUE, includeWhere.TD = TRUE, valueMapping.TDAster = structure(list(
        `NULL` = ""), .Names = "NULL"), valueMapping.Hadoop = structure(list(
        `NULL` = ""), .Names = "NULL")), .Names = c("FLRegrDataPrep.TDAster", 
"FLRegrDataPrep.TD", "FLTrainDataPrep.Hadoop", "FLTestDataPrep.Hadoop", 
"FLRegrDataPrepMD.TD", "FLWideToDeep.TDAster", "FLWideToDeep.Hadoop", 
"FLWideToDeep.TD", "FLDeepToWide.TDAster", ".", "FLKMeans.TDAster", 
"FLKMeans.TD", "FLKMeans.Hadoop", ".", "FLKMedoids.TDAster", 
"FLKMedoids.TD", "FLKMedoids.Hadoop", ".", "FLFKMeans.TDAster", 
".", "FLHKMeans.TDAster", "FLHKMeans.Hadoop", ".", "FLLinRegr.Hadoop", 
"FLLinRegr.TD", "FLLinRegr.TDAster", ".", "FLLinRegrMultiDataSet.TD", 
"FLLinRegrMultiDataSet.Hadoop", ".", "FLLinRegrScore.TD", "FLLinRegrScore.TDAster", 
"FLLinRegrScore.Hadoop", ".", "FLLogRegr.Hadoop", "FLLogRegr.TD", 
"FLLogRegr.TDAster", ".", "FLLogRegrMultiDataSet.TD", ".", "FLLogRegrScore.TD", 
"FLLogRegrScore.TDAster", "FLLogRegrScore.Hadoop", ".", "FLPoissonRegr.Hadoop", 
"FLPoissonRegr.TD", "FLPoissonRegr.TDAster", ".", "FLPoissonRegrScore.TD", 
"FLPoissonRegrScore.TDAster", ".", "FLVarCluster.TD", "FLVarCluster.Hadoop", 
".", "FLSystemTables.Hadoop", "FLSystemTables.TD", ".", "RANDOM.Hadoop", 
"RANDOM.TD", "prefix.TD", "prefix.TDAster", "prefix.Hadoop", 
"preArgs.TD", "preArgs.TDAster", "preArgs.Hadoop", "extraPars.TDAster", 
"withOutputPars.TD", "withOutputPars.TDAster", "withOutputPars.Hadoop", 
"withArgNames.TD", "withArgNames.TDAster", "argSeparator.TDAster", 
"withArgNames.Hadoop", "includeWhere.Hadoop", "includeWhere.TDAster", 
"includeWhere.TD", "valueMapping.TDAster", "valueMapping.Hadoop"
))
MatrixUDTMappingsFL <-
structure(list(FLMatrixInvUdt.TDAster = structure(list(funcName = "FLMatrixInvUdt", 
    platform = "TDAster", funcNamePlatform = "FLMatrixInvUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("partition1", 
    "row_id", "col_id", "matrix_inv"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixInvUdt.TD = structure(list(
    funcName = "FLMatrixInvUdt", platform = "TD", funcNamePlatform = "FLMatrixInvUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixInvUdt.Hadoop = structure(list(
    funcName = "FLMatrixInvUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixInverse", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "inverse_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLTridiagUdt.Hadoop = structure(list(
    funcName = "FLTridiagUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixTriDiag", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "tridiag_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLTridiagUdt.TD = structure(list(
    funcName = "FLTridiagUdt", platform = "TD", funcNamePlatform = "FLTridiagUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLCholeskyDecompUdt.Hadoop = structure(list(
    funcName = "FLCholeskyDecompUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixCholeskyDecomp", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "out_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLCholeskyDecompUdt.TD = structure(list(
    funcName = "FLCholeskyDecompUdt", platform = "TD", funcNamePlatform = "FLCholeskyDecompUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixDetUdt.Hadoop = structure(list(
    funcName = "FLMatrixDetUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixDeterminant", 
    args = c("OutputMatrixID", "OutputDetVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputDetVal"), .Names = c("matrix_id", "determinant_value"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLMatrixDetUdt.TD = structure(list(
    funcName = "FLMatrixDetUdt", platform = "TD", funcNamePlatform = "FLMatrixDetUdt", 
    args = c("OutputMatrixID", "OutputDetVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputDetVal"), .Names = c("OutputMatrixID", "OutputDetVal"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLEigenValueUdt.Hadoop = structure(list(
    funcName = "FLEigenValueUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixEigenSystem", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("vectorIDColumn", 
    "vectorIndexColumn", "vectorValueColumn"), .Names = c("matrix_id", 
    "row_id", "eigenvalue"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLEigenValueUdt.TD = structure(list(
    funcName = "FLEigenValueUdt", platform = "TD", funcNamePlatform = "FLEigenValueUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("vectorIDColumn", 
    "vectorIndexColumn", "vectorValueColumn"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputVal"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLEigenVectorUdt.Hadoop = structure(list(
    funcName = "FLEigenVectorUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixEigenSystem", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "eigenvector"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLEigenVectorUdt.TD = structure(list(
    funcName = "FLEigenVectorUdt", platform = "TD", funcNamePlatform = "FLEigenVectorUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixNormUdt.TD = structure(list(
    funcName = "FLMatrixNormUdt", platform = "TD", funcNamePlatform = "FLMatrixNormUdt", 
    args = c("OutputMatrixID", "OutputNorm"), argsPlatform = structure(c("outputmatrixid", 
    "outputnorm"), .Names = c("OutputMatrixID", "OutputNorm"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixNormUdt.Hadoop = structure(list(
    funcName = "FLMatrixNormUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixNorm", 
    args = c("OutputMatrixID", "OutputNorm"), argsPlatform = structure(c("outputmatrixid", 
    "outputnorm"), .Names = c("matrix_id", "value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixREFUdt.Hadoop = structure(list(
    funcName = "FLMatrixREFUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixREF", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "ref_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixREFUdt.TD = structure(list(
    funcName = "FLMatrixREFUdt", platform = "TD", funcNamePlatform = "FLMatrixREFUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixRREFUdt.Hadoop = structure(list(
    funcName = "FLMatrixRREFUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixRREF", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "rref_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixRREFUdt.TD = structure(list(
    funcName = "FLMatrixRREFUdt", platform = "TD", funcNamePlatform = "FLMatrixRREFUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLQRDecompUdt.Hadoop = structure(list(
    funcName = "FLQRDecompUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixQRDecomp", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputValQ", "OutputValR"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputValQ", "OutputValR"
    ), .Names = c("matrix_id", "row_id", "col_id", "q_matrix", 
    "r_matrix"))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLQRDecompUdt.TD = structure(list(funcName = "FLQRDecompUdt", 
    platform = "TD", funcNamePlatform = "FLQRDecompUdt", args = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputValQ", "OutputValR"
    ), argsPlatform = structure(c("OutputMatrixID", "OutputRowNum", 
    "OutputColNum", "OutputValQ", "OutputValR"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputValQ", "OutputValR"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLMatrixRankUdt.Hadoop = structure(list(
    funcName = "FLMatrixRankUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixRank", 
    args = c("OutputMatrixID", "OutputMtxRank"), argsPlatform = structure(c("OutputMatrixID", 
    "outputmtxrank"), .Names = c("matrix_id", "rank"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixRankUdt.TD = structure(list(
    funcName = "FLMatrixRankUdt", platform = "TD", funcNamePlatform = "FLMatrixRankUdt", 
    args = c("OutputMatrixID", "OutputMtxRank"), argsPlatform = structure(c("OutputMatrixID", 
    "outputmtxrank"), .Names = c("OutputMatrixID", "OutputMtxRank"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLMatrixRankUdt.TDAster = structure(list(
    funcName = "FLMatrixRankUdt", platform = "TDAster", funcNamePlatform = "FLMatrixRankUdt", 
    args = c("OutputMatrixID", "OutputMtxRank"), argsPlatform = structure(c("OutputMatrixID", 
    "outputmtxrank"), .Names = c("partition1", "outputmtxrank"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLMatrixPseudoInvUdt.TDAster = structure(list(
    funcName = "FLMatrixPseudoInvUdt", platform = "TDAster", 
    funcNamePlatform = "FLMatrixPseudoInvUdt", args = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("partition1", 
    "row_id", "col_id", "cell_val"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixPseudoInvUdt.TD = structure(list(
    funcName = "FLMatrixPseudoInvUdt", platform = "TD", funcNamePlatform = "FLMatrixPseudoInvUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixPseudoInvUdt.Hadoop = structure(list(
    funcName = "FLMatrixPseudoInvUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixPseudoInv", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "value"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLHessenbergDecompUdt.Hadoop = structure(list(
    funcName = "FLHessenbergDecompUdt", platform = "Hadoop", 
    funcNamePlatform = "FLPTFMatrixHessenbergDecomp", args = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputHVal", "OutputPVal"
    ), argsPlatform = structure(c("OutputMatrixID", "OutputRowNum", 
    "OutputColNum", "OutputHVal", "OutputPVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "h_matrix", "p_matrix"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLHessenbergDecompUdt.TD = structure(list(
    funcName = "FLHessenbergDecompUdt", platform = "TD", funcNamePlatform = "FLHessenbergDecompUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputValQ", "OutputValR"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputHVal", "OutputPVal"
    ), .Names = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputHVal", "OutputPVal"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLJordanDecompUdt.TDAster = structure(list(
    funcName = "FLJordanDecompUdt", platform = "TDAster", funcNamePlatform = "FLJordanDecompUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputHVal", "OutputPVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputHVal", "OutputPVal", 
    "OutPInvVal"), .Names = c("partition1", "row_id", "col_id", 
    "p_val", "j_val", "pinv_val"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLJordanDecompUdt.TD = structure(list(
    funcName = "FLJordanDecompUdt", platform = "TD", funcNamePlatform = "FLJordanDecompUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutPVal", "OutJVal", "OutPInvVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutPVal", "OutJVal", "OutPInvVal"
    ), .Names = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutPVal", "OutJVal", "OutPInvVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLLUDecompUdt.TDAster = structure(list(
    funcName = "FLLUDecompUdt", platform = "TDAster", funcNamePlatform = "FLLUDecompUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputValL", "OutputValU", "OutputPermut"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputValL", "OutputValU", 
    "OutputPermut"), .Names = c("partition1", "row_id", "col_id", 
    "l_val", "u_val", "permut"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLLUDecompUdt.TD = structure(list(
    funcName = "FLLUDecompUdt", platform = "TD", funcNamePlatform = "FLLUDecompUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputValL", "OutputValU", "OutputPermut"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputValL", "OutputValU", 
    "OutputPermut"), .Names = c("OutputMatrixID", "OutputRowNum", 
    "OutputColNum", "OutputValL", "OutputValU", "OutputPermut"
    ))), .Names = c("funcName", "platform", "funcNamePlatform", 
"args", "argsPlatform")), FLLUDecompUdt.Hadoop = structure(list(
    funcName = "FLLUDecompUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixLUDecomp", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputValL", "OutputValU", "OutputPermut"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputValL", "OutputValU", 
    "OutputPermut"), .Names = c("partition1", "row_id", "col_id", 
    "l_matrix", "u_matrix", "permut_matrix"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixInvExclUdt.TDAster = structure(list(
    funcName = "FLMatrixInvExclUdt", platform = "TDAster", funcNamePlatform = "FLMatrixInvExclUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("partition1", 
    "row_id", "col_id", "matrix_inv"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixInvExclUdt.TD = structure(list(
    funcName = "FLMatrixInvExclUdt", platform = "TD", funcNamePlatform = "FLMatrixInvExclUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixInvExclUdt.Hadoop = structure(list(
    funcName = "FLMatrixInvExclUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixInverseExcl", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutputVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutputVal"), .Names = c("matrix_id", 
    "row_id", "col_id", "inverse_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLSVUdt.Hadoop = structure(list(
    funcName = "FLSVUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixSV", 
    args = c("OutputMatrixID", "OutputID", "OutputSV"), argsPlatform = structure(c("vectorIDColumn", 
    "vectorIndexColumn", "vectorValueColumn"), .Names = c("matrix_id", 
    "output_id", "singular_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLSVUdt.TD = structure(list(
    funcName = "FLSVUdt", platform = "TD", funcNamePlatform = "FLSVUdt", 
    args = c("OutputMatrixID", "OutputID", "OutputSV"), argsPlatform = structure(c("vectorIDColumn", 
    "vectorIndexColumn", "vectorValueColumn"), .Names = c("OutputMatrixID", 
    "OutputID", "OutputSV"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLSVDUdt.Hadoop = structure(list(
    funcName = "FLSVDUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixSVD", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutUVal", "OutSVal", "OutVVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutUVal", "OutSVal", "OutVVal"
    ), .Names = c("matrix_id", "row_id", "col_id", "u_matrix", 
    "s_matrix", "v_matrix"))), .Names = c("funcName", "platform", 
"funcNamePlatform", "args", "argsPlatform")), FLSVDUdt.TD = structure(list(
    funcName = "FLSVDUdt", platform = "TD", funcNamePlatform = "FLSVDUdt", 
    args = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutUVal", "OutSVal", "OutVVal"), argsPlatform = structure(c("OutputMatrixID", 
    "OutputRowNum", "OutputColNum", "OutUVal", "OutSVal", "OutVVal"
    ), .Names = c("OutputMatrixID", "OutputRowNum", "OutputColNum", 
    "OutUVal", "OutSVal", "OutVVal"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), FLMatrixTrace.Hadoop = structure(list(
    funcName = "FLMatrixTrace", platform = "Hadoop", funcNamePlatform = "FLPTFMatrixTrace", 
    args = c("MatrixID", "MatrixTrace"), argsPlatform = structure(c("matrix_id", 
    "trace_value"), .Names = c("matrix_id", "trace_value"))), .Names = c("funcName", 
"platform", "funcNamePlatform", "args", "argsPlatform")), . = NULL, 
    FLModeUdt.TD = structure(list(funcName = "FLModeUdt", platform = "TD", 
        funcNamePlatform = "FLModeUdt", args = c("oGroupID", 
        "oMode"), argsPlatform = structure(c("oGroupID", "oMode"
        ), .Names = c("vectorIdColumn", "vectorValueColumn"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLModeUdt.Hadoop = structure(list(funcName = "FLModeUdt", 
        platform = "Hadoop", funcNamePlatform = "FLPTFMode", 
        args = c("oGroupID", "oMode"), argsPlatform = structure(c("GroupID", 
        "Value"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLMedianUdt.TD = structure(list(
        funcName = "FLMedianUdt", platform = "TD", funcNamePlatform = "FLMedianUdt", 
        args = c("oGroupID", "oMedian"), argsPlatform = structure(c("oGroupID", 
        "oMedian"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLMedianUdt.Hadoop = structure(list(
        funcName = "FLMedianUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMedian", 
        args = c("oGroupID", "oMedian"), argsPlatform = structure(c("GroupID", 
        "MedianValue"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLPercUdt.TD = structure(list(
        funcName = "FLPercUdt", platform = "TD", funcNamePlatform = "FLPercUdt", 
        args = c("oGroupID", "oPercVal"), argsPlatform = structure(c("oGroupID", 
        "oPercVal"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLPercUdt.Hadoop = structure(list(
        funcName = "FLPercUdt", platform = "Hadoop", funcNamePlatform = "FLPTFPerc", 
        args = c("oGroupID", "oPercVal"), argsPlatform = structure(c("GroupID", 
        "PercValue"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLPercentUdt.TD = structure(list(
        funcName = "FLPercentUdt", platform = "TD", funcNamePlatform = "FLPercentUdt", 
        args = c("oGroupID", "oObsID", "oPercentVal"), argsPlatform = structure(c("oObsID", 
        "oPercentVal"), .Names = c("vectorIndexColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLPercentUdt.Hadoop = structure(list(
        funcName = "FLPercentUdt", platform = "Hadoop", funcNamePlatform = "FLPTFPercent", 
        args = c("oGroupID", "oPercVal"), argsPlatform = structure(c("GroupID", 
        "PercValue"), .Names = c("vectorIndexColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLMeanAbsDevUdt.TD = structure(list(
        funcName = "FLMeanAbsDevUdt", platform = "TD", funcNamePlatform = "FLMeanAbsDevUdt", 
        args = c("oGroupID", "oMeanAbsDev"), argsPlatform = structure(c("oGroupID", 
        "oMeanAbsDev"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLMeanAbsDevUdt.Hadoop = structure(list(
        funcName = "FLMeanAbsDevUdt", platform = "Hadoop", funcNamePlatform = "FLPTFMeanAbsDev", 
        args = c("oGroupID", "oMeanAbsDev"), argsPlatform = structure(c("GroupID", 
        "Value"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLMedianAbsDevUdt.TD = structure(list(
        funcName = "FLMedianAbsDevUdt", platform = "TD", funcNamePlatform = "FLMedianAbsDevUdt", 
        args = c("oGroupID", "oMedianAbsDev"), argsPlatform = structure(c("oGroupID", 
        "oMedianAbsDev"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), FLMedianAbsDevUdt.Hadoop = structure(list(
        funcName = "FLMedianAbsDevUdt", platform = "Hadoop", 
        funcNamePlatform = "FLPTFMedianAbsDev", args = c("oGroupID", 
        "oMeanAbsDev"), argsPlatform = structure(c("GroupID", 
        "Value"), .Names = c("vectorIdColumn", "vectorValueColumn"
        ))), .Names = c("funcName", "platform", "funcNamePlatform", 
    "args", "argsPlatform")), . = NULL, FLFracRankUdt.TD = structure(list(
        funcName = "FLFracRankUdt", platform = "TD", funcNamePlatform = "FLFracRankUdt", 
        args = c("oGroupID", "oValue", "oFracRank"), argsPlatform = structure(c("oGroupID", 
        "oValue", "oFracRank"), .Names = c("vectorIdColumn", 
        "outputValueColumn", "vectorValueColumn"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLFracRankUdt.Hadoop = structure(list(funcName = "FLFracRankUdt", 
        platform = "Hadoop", funcNamePlatform = "FLPTFFracRank", 
        args = c("oGroupID", "oValue", "oFracRank"), argsPlatform = structure(c("GroupID", 
        "Value", "FracRank"), .Names = c("vectorIdColumn", "outputValueColumn", 
        "vectorValueColumn"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), . = NULL, FLPercRankUdt.TD = structure(list(
        funcName = "FLPercRankUdt", platform = "TD", funcNamePlatform = "FLPercRankUdt", 
        args = c("oGroupID", "oValue", "oPercRank"), argsPlatform = structure(c("oGroupID", 
        "oValue", "oPercRank"), .Names = c("vectorIdColumn", 
        "outputValueColumn", "vectorValueColumn"))), .Names = c("funcName", 
    "platform", "funcNamePlatform", "args", "argsPlatform")), 
    FLPercRankUdt.Hadoop = structure(list(funcName = "FLPercRankUdt", 
        platform = "Hadoop", funcNamePlatform = "FLPTFPercRank", 
        args = c("oGroupID", "oValue", "oPercRank"), argsPlatform = structure(c("GroupID", 
        "Value", "PercRank"), .Names = c("vectorIdColumn", "outputValueColumn", 
        "vectorValueColumn"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), . = NULL, FLRankUdt.TD = structure(list(
        funcName = "FLRankUdt", platform = "TD", funcNamePlatform = "FLRankUdt", 
        args = c("oGroupID", "oValue", "oRank"), argsPlatform = structure(c("oGroupID", 
        "oValue", "oRank"), .Names = c("vectorIdColumn", "outputValueColumn", 
        "vectorValueColumn"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform")), FLRankUdt.Hadoop = structure(list(
        funcName = "FLRankUdt", platform = "Hadoop", funcNamePlatform = "FLPTFRank", 
        args = c("oGroupID", "oValue", "oRank"), argsPlatform = structure(c("GroupID", 
        "Value", "ValueRank"), .Names = c("vectorIdColumn", "outputValueColumn", 
        "vectorValueColumn"))), .Names = c("funcName", "platform", 
    "funcNamePlatform", "args", "argsPlatform"))), .Names = c("FLMatrixInvUdt.TDAster", 
"FLMatrixInvUdt.TD", "FLMatrixInvUdt.Hadoop", "FLTridiagUdt.Hadoop", 
"FLTridiagUdt.TD", "FLCholeskyDecompUdt.Hadoop", "FLCholeskyDecompUdt.TD", 
"FLMatrixDetUdt.Hadoop", "FLMatrixDetUdt.TD", "FLEigenValueUdt.Hadoop", 
"FLEigenValueUdt.TD", "FLEigenVectorUdt.Hadoop", "FLEigenVectorUdt.TD", 
"FLMatrixNormUdt.TD", "FLMatrixNormUdt.Hadoop", "FLMatrixREFUdt.Hadoop", 
"FLMatrixREFUdt.TD", "FLMatrixRREFUdt.Hadoop", "FLMatrixRREFUdt.TD", 
"FLQRDecompUdt.Hadoop", "FLQRDecompUdt.TD", "FLMatrixRankUdt.Hadoop", 
"FLMatrixRankUdt.TD", "FLMatrixRankUdt.TDAster", "FLMatrixPseudoInvUdt.TDAster", 
"FLMatrixPseudoInvUdt.TD", "FLMatrixPseudoInvUdt.Hadoop", "FLHessenbergDecompUdt.Hadoop", 
"FLHessenbergDecompUdt.TD", "FLJordanDecompUdt.TDAster", "FLJordanDecompUdt.TD", 
"FLLUDecompUdt.TDAster", "FLLUDecompUdt.TD", "FLLUDecompUdt.Hadoop", 
"FLMatrixInvExclUdt.TDAster", "FLMatrixInvExclUdt.TD", "FLMatrixInvExclUdt.Hadoop", 
"FLSVUdt.Hadoop", "FLSVUdt.TD", "FLSVDUdt.Hadoop", "FLSVDUdt.TD", 
"FLMatrixTrace.Hadoop", ".", "FLModeUdt.TD", "FLModeUdt.Hadoop", 
"FLMedianUdt.TD", "FLMedianUdt.Hadoop", ".", "FLPercUdt.TD", 
"FLPercUdt.Hadoop", ".", "FLPercentUdt.TD", "FLPercentUdt.Hadoop", 
".", "FLMeanAbsDevUdt.TD", "FLMeanAbsDevUdt.Hadoop", ".", "FLMedianAbsDevUdt.TD", 
"FLMedianAbsDevUdt.Hadoop", ".", "FLFracRankUdt.TD", "FLFracRankUdt.Hadoop", 
".", "FLPercRankUdt.TD", "FLPercRankUdt.Hadoop", ".", "FLRankUdt.TD", 
"FLRankUdt.Hadoop"))
